beers = {'Blue Point Brewing No A pologies': {'abv': '10%',
                                      'baScore': u'87',
                                      'baUrl': u'http://beeradvocate.com/beer/profile/764/34972',
                                      'description': 'Our Imperial or Double IPA is a brew not to be taken lightly.  Crafted in small batches from the finest European malts and American hops.  A huge earthy hop aroma is followed by a pleasant caramel sweetness.  Four hop varieties round out this perfectly balanced beer that is sure to warm your soul and for that we offer No Apologies',
                                      'id': 30,
                                      'name': 'Blue Point No Apologies Imperial IPA',
                                      'originalName': 'Blue Point Brewing No A pologies',
                                      'rbScore': '94',
                                      'rbUrl': u'http://www.ratebeer.com/beer/blue-point-no-apologies-imperial-ipa/69194/',
                                      'result': {u'Description': u'Ratings for Blue Point No Apologies Imperial IPA; American Double / Imperial IPA style beer brewed by Blue Point Brewing Company in Patchogue, NY. 87 out of 100 with ...',
                                                 u'DisplayUrl': u'beeradvocate.com/beer/profile/764/34972',
                                                 u'ID': u'544da54b-5ef8-4bde-a6e7-75a4828817d4',
                                                 u'Title': u'Blue Point No Apologies Imperial IPA - Blue Point Brewing Company ...',
                                                 u'Url': u'http://beeradvocate.com/beer/profile/764/34972',
                                                 u'__metadata': {u'type': u'WebResult',
                                                                 u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Blue Point Brewing No A pologies "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                      'style': 'Imperial/Double IPA'},
 'Boulder Beer Mojo IPA': {'abv': '7.2%',
                           'baScore': u'86',
                           'baUrl': u'http://beeradvocate.com/beer/profile/130/12322',
                           'description': 'Mo-Jo: 1: A magic spell or charm; magical power; 2. Herbaceous ale that summons hop attacks. \r\n',
                           'id': 18,
                           'name': 'Boulder Beer Mojo IPA',
                           'originalName': 'Boulder Beer Mojo IPA',
                           'rbScore': '94',
                           'rbUrl': u'http://www.ratebeer.com/beer/boulder-beer-mojo-ipa/25095/',
                           'result': {u'Description': u'... American IPA style beer brewed by Boulder Beer ... Boulder Mojo India Pale Ale pours from the bottle to a gold/tan ... 86 out of 100 based on 1,197 ...',
                                      u'DisplayUrl': u'beeradvocate.com/beer/profile/130/12322',
                                      u'ID': u'efe66de1-6b1b-4f38-a719-0e0ae46d375a',
                                      u'Title': u'Mojo IPA - Boulder Beer / Wilderness Pub - Boulder, CO - BeerAdvocate',
                                      u'Url': u'http://beeradvocate.com/beer/profile/130/12322',
                                      u'__metadata': {u'type': u'WebResult',
                                                      u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Boulder Beer Mojo IPA "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                           'style': 'India Pale Ale (IPA)'},
 'Bud Light': {'abv': '4.1%',
               'baScore': u'47',
               'baUrl': u'http://beeradvocate.com/beer/profile/29/1320/?ba=jkball01',
               'description': 'Introduced nationally in 1982, Bud Light is brewed with a malt and hops ratio different from Budweiser for a distinctively crisp taste with fewer calories.',
               'id': 32,
               'name': 'Bud Light',
               'originalName': 'Bud Light',
               'rbScore': '0',
               'rbUrl': u'http://www.ratebeer.com/beer/bud-light/474/',
               'result': {u'Description': u'Ratings for Bud Light; Light Lager style beer brewed by Anheuser-Busch in Saint Louis, ... 47 out of 100 based on 2,887 user ratings. Sign Up Now!',
                          u'DisplayUrl': u'beeradvocate.com/beer/profile/29/1320/?ba=jkball01',
                          u'ID': u'bd555d98-100e-4abe-8fce-f05781792283',
                          u'Title': u'Bud Light - Anheuser-Busch - Saint Louis, MO - BeerAdvocate',
                          u'Url': u'http://beeradvocate.com/beer/profile/29/1320/?ba=jkball01',
                          u'__metadata': {u'type': u'WebResult',
                                          u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Bud Light "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
               'style': 'Pale Lager'},
 'Devils Backbone Brewing 8 Point IPA': {'abv': '5.9%',
                                         'baScore': u'85',
                                         'baUrl': u'http://beeradvocate.com/beer/profile/18539/46157',
                                         'description': 'This pale bronze beer is medium in body with intense hop flavor and aroma. Our IPA is brewed in the style of the \xc2\x93west coast\xc2\x94 with robust hop character coming from American grown varieties of hops. IPA\xc2\x92s are amongst the most popular craft brewed beers as they have moderate strength and tons of flavor. This is not your Grandfathers beer',
                                         'id': 28,
                                         'name': 'Devils Backbone Eight Point IPA',
                                         'originalName': 'Devils Backbone Brewing 8 Point IPA',
                                         'rbScore': '92',
                                         'rbUrl': u'http://www.ratebeer.com/beer/devils-backbone-eight-point-ipa/95542/',
                                         'result': {u'Description': u'Ratings for Eight Point IPA; American IPA style beer brewed by Devils Backbone Brewing Company in Roseland, ... 85 out of 100 based on 181 user ratings.',
                                                    u'DisplayUrl': u'beeradvocate.com/beer/profile/18539/46157',
                                                    u'ID': u'e820bad9-6b7d-4af5-8cd0-5f580b65e187',
                                                    u'Title': u'Eight Point IPA - Devils Backbone Brewing Company - Roseland, VA ...',
                                                    u'Url': u'http://beeradvocate.com/beer/profile/18539/46157',
                                                    u'__metadata': {u'type': u'WebResult',
                                                                    u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Devils Backbone Brewing 8 Point IPA "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                         'style': 'India Pale Ale (IPA)'},
 'Devils Backbone Schwartz Bier Black Lager': {'abv': '4.9%',
                                               'baScore': u'86',
                                               'baUrl': u'http://beeradvocate.com/beer/profile/18539/51397',
                                               'description': 'A German-style black lager. Hints of caramel and coffee blend in this light to medium dark lager. Do not let the color fool you, this beer goes down very easy. May the schwartz be with you',
                                               'id': 3,
                                               'name': 'Devils Backbone Schwartz Bier',
                                               'originalName': 'Devils Backbone Schwartz Bier Black Lager',
                                               'rbScore': '80',
                                               'rbUrl': u'http://www.ratebeer.com/beer/devils-backbone-schwartz-bier/107323/',
                                               'result': {u'Description': u'Schwartz Bier - Devils Backbone Brewing Company. Displayed for educational use only; do not reuse. Tweet. ... 86 out of 100 based on 26 user ratings. Sign Up Now!',
                                                          u'DisplayUrl': u'beeradvocate.com/beer/profile/18539/51397',
                                                          u'ID': u'119f10b5-267b-4609-9acd-b26b388d0694',
                                                          u'Title': u'Schwartz Bier - Devils Backbone Brewing Company - Roseland, VA ...',
                                                          u'Url': u'http://beeradvocate.com/beer/profile/18539/51397',
                                                          u'__metadata': {u'type': u'WebResult',
                                                                          u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Devils Backbone Schwartz Bier Black Lager "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                               'style': 'Schwarzbier'},
 'Dogfish Head 61 IPA': {'abv': '6%',
                         'baScore': u'81',
                         'baUrl': u'http://beeradvocate.com/beer/profile/10099/91677',
                         'description': 'Our flagship beer. A session India Pale Ale brewed with Warrior, Amarillo &amp; \xc2\x92Mystery Hop X.\xc2\x92 A powerful East Coast I.P.A. with a lot of citrusy hop character. THE session beer for beer geeks like us',
                         'id': 2,
                         'name': 'Dogfish Head 60 Minute IPA',
                         'originalName': 'Dogfish Head 61 IPA',
                         'rbScore': '98',
                         'rbUrl': u'http://www.ratebeer.com/beer/dogfish-head-60-minute-ipa/7431/',
                         'result': {u'Description': u'Ratings for Sixty-One (61); American IPA style beer brewed by Dogfish Head Brewery in Milton, ... 81 out of 100 based on 466 user ratings. Sign Up Now!',
                                    u'DisplayUrl': u'beeradvocate.com/beer/profile/10099/91677',
                                    u'ID': u'aaa23059-7e51-4a26-ac64-94d0e24e8d5e',
                                    u'Title': u'Sixty-One (61) - Dogfish Head Brewery - Milton, DE - BeerAdvocate',
                                    u'Url': u'http://beeradvocate.com/beer/profile/10099/91677',
                                    u'__metadata': {u'type': u'WebResult',
                                                    u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Dogfish Head 61 IPA "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                         'style': 'India Pale Ale (IPA)'},
 'Dogfish Head Rhizing Bines IPA': {'abv': '8%',
                                    'baScore': u'83',
                                    'baUrl': u'http://beeradvocate.com/beer/profile/10099/89024',
                                    'description': 'Rhizing Bines is a collaborative IPA using the best of both coasts: Carolina-grown red fife wheat and Dogfish Head\xc2\x92s continual-hopping from the East and Sierra Nevada\xc2\x92s estate-grown caramel malt and Torpedo dry-hopping from the west.',
                                    'id': 13,
                                    'name': 'Dogfish Head Life &amp; Limb Rhizing Bines',
                                    'originalName': 'Dogfish Head Rhizing Bines IPA',
                                    'rbScore': '90',
                                    'rbUrl': u'http://www.ratebeer.com/beer/dogfish-head-life-limb-rhizing-bines/200863/',
                                    'result': {u'Description': u'Ratings for Rhizing Bines; American Double / Imperial IPA style beer brewed by Dogfish Head Brewery in Milton, ... 83 out of 100 based on 528 user ratings.',
                                               u'DisplayUrl': u'beeradvocate.com/beer/profile/10099/89024',
                                               u'ID': u'3a1e7a01-251f-4ea6-b16a-78a56634c6ac',
                                               u'Title': u'Rhizing Bines - Dogfish Head Brewery - Milton, DE - BeerAdvocate',
                                               u'Url': u'http://beeradvocate.com/beer/profile/10099/89024',
                                               u'__metadata': {u'type': u'WebResult',
                                                               u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Dogfish Head Rhizing Bines IPA "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                    'style': 'Imperial/Double IPA'},
 'DuCIaw Hell R azer IPA': {'abv': '',
                            'baScore': '??',
                            'baUrl': 'http://google.com/?q=DuCIaw Hell R azer IPA',
                            'description': '',
                            'id': 25,
                            'name': 'DuCIaw Hell R azer IPA',
                            'originalName': 'DuCIaw Hell R azer IPA',
                            'rbScore': '??',
                            'rbUrl': 'http://google.com/?q=DuCIaw Hell R azer IPA',
                            'result': '',
                            'style': ''},
 'Flying Dog Pumpernickel IPA': {'abv': '7%',
                                 'baScore': u'83',
                                 'baUrl': u'http://beeradvocate.com/beer/profile/68/91538/?ba=Boone757',
                                 'description': 'This bready brew begins with notes of citrus, earthiness, roast, and caraway spice. Those rich aromas give way to creamy, malty chocolate and biscuit notes balance with smooth bitterness and caraway spice. ',
                                 'id': 8,
                                 'name': 'Flying Dog Pumpernickel IPA',
                                 'originalName': 'Flying Dog Pumpernickel IPA',
                                 'rbScore': '79',
                                 'rbUrl': u'http://www.ratebeer.com/beer/flying-dog-pumpernickel-ipa/204105/',
                                 'result': {u'Description': u'Pumpernickel IPA - Flying Dog Brewery. No picture uploaded. Have one? Upload it now. Tweet. BA SCORE 83 good- ... 83 out of 100 based on 25 user ratings. Sign Up Now!',
                                            u'DisplayUrl': u'beeradvocate.com/beer/profile/68/91538/?ba=Boone757',
                                            u'ID': u'2168ffb9-6b01-43bb-850e-5c4f4e5d034e',
                                            u'Title': u'Pumpernickel IPA - Flying Dog Brewery - Frederick, MD - BeerAdvocate',
                                            u'Url': u'http://beeradvocate.com/beer/profile/68/91538/?ba=Boone757',
                                            u'__metadata': {u'type': u'WebResult',
                                                            u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Flying Dog Pumpernickel IPA "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                 'style': 'Black IPA'},
 'Flying Dog Raging Bitch IPA': {'abv': '8.3%',
                                 'baScore': u'89',
                                 'baUrl': u'http://beeradvocate.com/beer/profile/68/52855',
                                 'description': 'Flying Dog Brewery will celebrate its 20th Anniversary a few months early on Friday, September 25th (the brewery turns 20 next year). The brewery will be sampling the new Raging Bitch Belgian-style India Pale Ale at the Flying dog Brats And Gonzo party in Denver that day as part of the Great American Beer Fest happening that week (unscramble the FBAG acronym to get GABF). More info about the fest can be found on the official Flying Dog blog.\r\n\r\nThe beer also appeared on draft at this past weekend\xc2\x92s Gonzofest party. Al from Hop Talk was in attendance and reported on his blog, \xc2\x93I understand it\xc2\x92s made from an augmented Snake Dog wort with an exclusive Belgian yeast strain (called Diablo) and dry-hopped with a load of Amarillo hops. They\xc2\x92re calling it a Belgian IPA. It was really good. It had that hop bite from a big, bad American IPA with the banana and bubblegum from the Belgian yeast.\xc2\x94\r\n\r\nSome may remember a beer called, Raging Bitch Birch Beer, that Flying Dog introduced on April 1st. Whereas that low-gravity series beer was a joke, this beer is anything but at 8% ABV (60 IBU).\r\n\r\nPropaganda from the label: \xc2\x93Two inflammatory words\xc2\x85one wild drink. Nectar imprisoned in a bottle. Let it out. It is cruel to keep a wild animal locked up. Uncap it. Release it\xc2\x85stand back',
                                 'id': 26,
                                 'name': 'Flying Dog Raging Bitch',
                                 'originalName': 'Flying Dog Raging Bitch IPA',
                                 'rbScore': '98',
                                 'rbUrl': u'http://www.ratebeer.com/beer/flying-dog-raging-bitch/110932/',
                                 'result': {u'Description': u'Ratings for Raging Bitch Belgian-Style IPA; Belgian IPA style beer brewed by Flying Dog Brewery in Frederick, ... 89 out of 100 based on 2,059 user ratings.',
                                            u'DisplayUrl': u'beeradvocate.com/beer/profile/68/52855',
                                            u'ID': u'e0c61b51-3aa7-4dee-9a1c-544b1342b1e7',
                                            u'Title': u'Raging Bitch Belgian-Style IPA - Flying Dog Brewery - Frederick ...',
                                            u'Url': u'http://beeradvocate.com/beer/profile/68/52855',
                                            u'__metadata': {u'type': u'WebResult',
                                                            u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Flying Dog Raging Bitch IPA "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                 'style': 'India Pale Ale (IPA)'},
 'Flying Dog Single Hop Galaxy': {'abv': '10%',
                                  'baScore': u'88',
                                  'baUrl': u'http://beeradvocate.com/beer/profile/68/89399',
                                  'description': 'You call that a hop? THIS is a hop. Developed and grown solely in Australia, Galaxy hops impart distinctive grapefruit and passionfruit character from when the beer first greets the nose until the last of it lingers on the palate. Combined with a crisp, dry finish, our last Single Hop Imperial IPA release of 2012 will leave you begging for more. Number of obnoxious references to Australian pop culture used: 1. Number of obnoxious references to Australian pop culture we wanted to use: 20.',
                                  'id': 10,
                                  'name': 'Flying Dog Imperial IPA - Galaxy Single Hop',
                                  'originalName': 'Flying Dog Single Hop Galaxy',
                                  'rbScore': '95',
                                  'rbUrl': u'http://www.ratebeer.com/beer/flying-dog-imperial-ipa--galaxy-single-hop/194112/',
                                  'result': {u'Description': u'Ratings for Single Hop Imperial IPA (Galaxy); American Double / Imperial IPA style beer brewed by Flying Dog Brewery in ... 88 out of 100 based on 31 user ratings.',
                                             u'DisplayUrl': u'beeradvocate.com/beer/profile/68/89399',
                                             u'ID': u'26acef2f-f25d-4d24-934f-fd32c63abd01',
                                             u'Title': u'Single Hop Imperial IPA (Galaxy) - Flying Dog Brewery - Frederick ...',
                                             u'Url': u'http://beeradvocate.com/beer/profile/68/89399',
                                             u'__metadata': {u'type': u'WebResult',
                                                             u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Flying Dog Single Hop Galaxy "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                  'style': 'Imperial/Double IPA'},
 'Fox Barrel Blackberry Pear Cider': {'abv': '4.5%',
                                      'baScore': u'93',
                                      'baUrl': u'http://beeradvocate.com/beer/profile/24018/80525/?ba=Bonko_the_sane',
                                      'description': 'Our Hard Pear Cider is a dryer, soft bodied cider which is light and refreshing. It\xc2\x92s an excellent candidate in situations where you might consider a dry Gewurtztraminer or champagne. Excellent with fruits, cheeses and salads, this light beverage is also a great brunch choice. Try it with orange juice for a "Fox-mosa".',
                                      'id': 6,
                                      'name': 'Fox Barrel Pear Cider',
                                      'originalName': 'Fox Barrel Blackberry Pear Cider',
                                      'rbScore': '53',
                                      'rbUrl': u'http://www.ratebeer.com/beer/fox-barrel-pear-cider/53606/',
                                      'result': {u'Description': u'Primary flavors are cherry pie, blackberry/red raspberry, toasted biscuit, cola, espresso, and mocha, in that order. ... 93 out of 100 based on 183 user ratings.',
                                                 u'DisplayUrl': u'beeradvocate.com/beer/profile/24018/80525/?ba=Bonko_the_sane',
                                                 u'ID': u'eab94b72-39c6-49a3-a8f2-17eed356bcc7',
                                                 u'Title': u'Funk Metal Sour Barrel-Aged Stout - Jester King Craft Brewery ...',
                                                 u'Url': u'http://beeradvocate.com/beer/profile/24018/80525/?ba=Bonko_the_sane',
                                                 u'__metadata': {u'type': u'WebResult',
                                                                 u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Fox Barrel Blackberry Pear Cider "out of 100 based on" site:beeradvocate.com\'&$skip=4&$top=1'}},
                                      'style': 'Perry'},
 'Full Tilt F leet Street Raspberry Wheat': {'abv': '4.5%',
                                             'baScore': '??',
                                             'baUrl': u'http://beeradvocate.com/beer/profile/31238/92109',
                                             'description': 'The first beer of it\xc2\x92s kind',
                                             'id': 24,
                                             'name': 'Full Tilt F leet Street Raspberry Wheat',
                                             'originalName': 'Full Tilt F leet Street Raspberry Wheat',
                                             'rbScore': '??',
                                             'rbUrl': u'http://www.ratebeer.com/beer/war-horse-riesling-ale/112933/',
                                             'result': {u'Description': u'Ratings for Fleet Street Raspberry Wheat; Fruit / Vegetable Beer style beer brewed by Full Tilt Brewing in Baltimore, MD. ... N/A out of 100 based on 7 user ratings.',
                                                        u'DisplayUrl': u'beeradvocate.com/beer/profile/31238/92109',
                                                        u'ID': u'25170547-4fe9-4b1c-ac36-1f1a5363096a',
                                                        u'Title': u'Fleet Street Raspberry Wheat - Full Tilt Brewing - Baltimore, MD ...',
                                                        u'Url': u'http://beeradvocate.com/beer/profile/31238/92109',
                                                        u'__metadata': {u'type': u'WebResult',
                                                                        u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Full Tilt F leet Street Raspberry Wheat "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                             'style': 'Fruit Beer'},
 'Goose Island Summertime': {'abv': '5%',
                             'baScore': u'81',
                             'baUrl': u'http://beeradvocate.com/beer/profile/1146/1171',
                             'description': 'Kolsch, the clean and refreshing beer style of Cologne, Germany, quenches summertime thirst. This pale golden ale with a lightly fruity aroma is cold-conditioned or lagered after its primary fermentation. More simply, our Summertime uses only the finest malts and German hops to create the perfect beer for hot Summer days and warm Summer nights.',
                             'id': 12,
                             'name': 'Goose Island Summertime ',
                             'originalName': 'Goose Island Summertime',
                             'rbScore': '48',
                             'rbUrl': u'http://www.ratebeer.com/beer/goose-island-summertime/817/',
                             'result': {u'Description': u'Summertime - Goose Island Beer Co. Displayed for educational use only; do not reuse. Tweet. BA SCORE 81 ... 81 out of 100 based on 791 user ratings. Sign Up Now!',
                                        u'DisplayUrl': u'beeradvocate.com/beer/profile/1146/1171',
                                        u'ID': u'ab397800-08cb-4f7c-a0b3-00362d01b356',
                                        u'Title': u'Summertime - Goose Island Beer Co. - Chicago, IL - BeerAdvocate',
                                        u'Url': u'http://beeradvocate.com/beer/profile/1146/1171',
                                        u'__metadata': {u'type': u'WebResult',
                                                        u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Goose Island Summertime "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                             'style': 'K\xc3\xb6lsch'},
 'Guinness Stout': {'abv': '',
                    'baScore': u'92',
                    'baUrl': u'http://beeradvocate.com/beer/profile/209/752/?ba=menacho1',
                    'description': '',
                    'id': 31,
                    'name': 'Guinness Stout',
                    'originalName': 'Guinness Stout',
                    'rbScore': '??',
                    'rbUrl': u'http://www.ratebeer.com/Beer/guinness-draught/1267/',
                    'result': {u'Description': u'Ratings for Guinness Foreign Extra Stout; Foreign / Export Stout style beer brewed by Guinness Ltd. in Dublin, ... 92 out of 100 based on 1,379 user ratings.',
                               u'DisplayUrl': u'beeradvocate.com/beer/profile/209/752/?ba=menacho1',
                               u'ID': u'7b66ab08-ef8b-4866-a9ef-b1f0dce8c033',
                               u'Title': u'Guinness Foreign Extra Stout - Guinness Ltd. - Dublin, Ireland ...',
                               u'Url': u'http://beeradvocate.com/beer/profile/209/752/?ba=menacho1',
                               u'__metadata': {u'type': u'WebResult',
                                               u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Guinness Stout "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                    'style': ''},
 'Heavy Seas Below Decks Barley Wine Cabernet Barrel Aged': {'abv': '10%',
                                                             'baScore': u'88',
                                                             'baUrl': u'http://beeradvocate.com/beer/profile/898/58430',
                                                             'description': 'This English style Barleywine Ale has been aged in cabernet wine barrels. Enjoy now or cellar it "Below Decks" as it will become more complex as it ages. ',
                                                             'id': 15,
                                                             'name': 'Heavy Seas Mutiny Fleet Below Decks Cabernet Barrel Aged',
                                                             'originalName': 'Heavy Seas Below Decks Barley Wine Cabernet Barrel Aged',
                                                             'rbScore': '96',
                                                             'rbUrl': u'http://www.ratebeer.com/beer/heavy-seas-mutiny-fleet-below-decks-cabernet-barrel-aged/123103/',
                                                             'result': {u'Description': u'Heavy Seas Cabernet Barrel Aged Below Decks from Heavy Seas Beer. 88 out of 100 based on 122 user ratings. Sign Up Now! Rate, Review & Track This Beer!',
                                                                        u'DisplayUrl': u'beeradvocate.com/beer/profile/898/58430',
                                                                        u'ID': u'153ed38e-6c58-448b-b4bf-076531f4685f',
                                                                        u'Title': u'Heavy Seas Cabernet Barrel Aged Below Decks - Heavy Seas Beer ...',
                                                                        u'Url': u'http://beeradvocate.com/beer/profile/898/58430',
                                                                        u'__metadata': {u'type': u'WebResult',
                                                                                        u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Heavy Seas Below Decks Barley Wine Cabernet Barrel Aged "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                                             'style': 'Barley Wine'},
 'Heavy Seas Black Cannon Black IPA': {'abv': '7.25%',
                                       'baScore': u'86',
                                       'baUrl': u'http://beeradvocate.com/beer/profile/898/65545',
                                       'description': 'While the style is an oxymoron, this ale is an variation of our "Loose Cannon" IPA with an obvious dark note.',
                                       'id': 14,
                                       'name': 'Heavy Seas Black Cannon',
                                       'originalName': 'Heavy Seas Black Cannon Black IPA',
                                       'rbScore': '91',
                                       'rbUrl': u'http://www.ratebeer.com/beer/heavy-seas-black-cannon/134469/',
                                       'result': {u'Description': u'Ratings for Heavy Seas Black Cannon; American Black Ale style beer brewed by Heavy Seas Beer in Baltimore, ... 86 out of 100 based on 465 user ratings.',
                                                  u'DisplayUrl': u'beeradvocate.com/beer/profile/898/65545',
                                                  u'ID': u'4f3cd994-5c3e-494e-a0e7-878e7e2dd084',
                                                  u'Title': u'Heavy Seas Black Cannon - Heavy Seas Beer - Baltimore, MD ...',
                                                  u'Url': u'http://beeradvocate.com/beer/profile/898/65545',
                                                  u'__metadata': {u'type': u'WebResult',
                                                                  u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Heavy Seas Black Cannon Black IPA "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                       'style': 'Black IPA'},
 'Long Trail Pollenator Spring Ale': {'abv': '5%',
                                      'baScore': u'83',
                                      'baUrl': u'http://beeradvocate.com/beer/profile/94/271',
                                      'description': 'Copper-colored ale is medium-bodied and highly hopped. Its flavor is delightfully complex: tangy fruit at the start, with an assertive hop crispness and a long malty palate that one well-known beer writer has compared to the flavor of freshly-baked bread.',
                                      'id': 4,
                                      'name': 'Smuttynose Shoals Pale Ale',
                                      'originalName': 'Long Trail Pollenator Spring Ale',
                                      'rbScore': '88',
                                      'rbUrl': u'http://www.ratebeer.com/beer/smuttynose-shoals-pale-ale/103/',
                                      'result': {u'Description': u'Ratings for Hibernator; Scottish Ale style beer brewed by Long Trail Brewing Co. in Bridgewaters Corners, VT. 83 out of 100 with 507 BeerAdvocate opinions.',
                                                 u'DisplayUrl': u'beeradvocate.com/beer/profile/94/271',
                                                 u'ID': u'dfde168f-bdd6-48ac-b742-d323c1e0f448',
                                                 u'Title': u'Hibernator - Long Trail Brewing Co. - Bridgewaters Corners, VT ...',
                                                 u'Url': u'http://beeradvocate.com/beer/profile/94/271',
                                                 u'__metadata': {u'type': u'WebResult',
                                                                 u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Long Trail Pollenator Spring Ale "out of 100 based on" site:beeradvocate.com\'&$skip=3&$top=1'}},
                                      'style': 'English Pale Ale'},
 'Nectar Ales IPA': {'abv': '6.7%',
                     'baScore': u'87',
                     'baUrl': u'http://beeradvocate.com/beer/profile/17963/9024',
                     'description': 'Our IPA is created from a base of Pale and Crystal malts and is aggressively hopped throughout the brewing process with a final hop addition in the conditioning vessel. A beautiful flowery hop aroma will greet you as you dive into this hop lover\xc2\x92s dream. A middle caramel malt presence balances high hop bitterness with hop flavor end to end... learn to love hops',
                     'id': 27,
                     'name': 'Nectar Ales Nectar IPA',
                     'originalName': 'Nectar Ales IPA',
                     'rbScore': '96',
                     'rbUrl': u'http://www.ratebeer.com/beer/nectar-ales-nectar-ipa/12679/',
                     'result': {u'Description': u'Ratings for Nectar IPA; American IPA style beer brewed by Nectar Ales in Paso Robles, ... 87 out of 100 based on 434 user ratings. Sign Up Now!',
                                u'DisplayUrl': u'beeradvocate.com/beer/profile/17963/9024',
                                u'ID': u'8d4a2416-3e98-431e-a992-94216935b3fe',
                                u'Title': u'Nectar IPA - Nectar Ales - Paso Robles, CA - BeerAdvocate',
                                u'Url': u'http://beeradvocate.com/beer/profile/17963/9024',
                                u'__metadata': {u'type': u'WebResult',
                                                u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Nectar Ales IPA "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                     'style': 'India Pale Ale (IPA)'},
 'New Belgium Ranger IPA': {'abv': '6.5%',
                            'baScore': u'86',
                            'baUrl': u'http://beeradvocate.com/beer/profile/192/55081',
                            'description': 'Are you a hopinista? Thank our Beer Rangers for inspiring (and begging for) this well-balanced Simcoe, Cascade and Chinook hopped IPA. 70 IBUs',
                            'id': 16,
                            'name': 'New Belgium Ranger IPA',
                            'originalName': 'New Belgium Ranger IPA',
                            'rbScore': '95',
                            'rbUrl': u'http://www.ratebeer.com/beer/new-belgium-ranger-ipa/108325/',
                            'result': {u'Description': u"New Belgium Brewing's Ranger India Pale Ale 3.79/5.00 Serving type: bottle 05-10-2013 21:59:39 | More by Jadjunk. ... 86 out of 100 based on 2,521 user ratings.",
                                       u'DisplayUrl': u'beeradvocate.com/beer/profile/192/55081',
                                       u'ID': u'23a2fbf9-4554-442a-b5a2-1662b7ee4a03',
                                       u'Title': u'Ranger - New Belgium Brewing - Fort Collins, CO - BeerAdvocate',
                                       u'Url': u'http://beeradvocate.com/beer/profile/192/55081',
                                       u'__metadata': {u'type': u'WebResult',
                                                       u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'New Belgium Ranger IPA "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                            'style': 'India Pale Ale (IPA)'},
 'No ': {'abv': '8.5%',
         'baScore': u'84',
         'baUrl': u'http://beeradvocate.com/beer/profile/24326/76495',
         'description': 'cask, occasional. Bottled. Aged in Compte De Lauvia 1990 vintage Armagnac barrels',
         'id': 1,
         'name': 'Fuller\xe2\x80\x99s Brewers Reserve Limited Edition No 4 Oak Aged Ale Armagnac',
         'originalName': 'No ',
         'rbScore': '94',
         'rbUrl': u'http://www.ratebeer.com/beer/fullers-brewers-reserve-limited-edition-no-4-oak-aged-ale-armagnac/181716/',
         'result': {u'Description': u'No bitterness on the finish; with lingering notes of dark chocolate, caramel, toffee, butterscotch, ... 84 out of 100 based on 35 user ratings. Sign Up Now!',
                    u'DisplayUrl': u'beeradvocate.com/beer/profile/24326/76495',
                    u'ID': u'b452b5b3-a010-43a4-b298-89bd9cb3ea90',
                    u'Title': u'Elda M Milk Stout - No Label Brewing Company - Katy, TX - BeerAdvocate',
                    u'Url': u'http://beeradvocate.com/beer/profile/24326/76495',
                    u'__metadata': {u'type': u'WebResult',
                                    u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'No  "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
         'style': 'English Strong Ale'},
 'Rogue Chipotle Ale': {'abv': '5.5%',
                        'baScore': u'81',
                        'baUrl': u'http://beeradvocate.com/beer/profile/132/354',
                        'description': 'Dedicated to Spanish author Juan de la Cueva, who, in 1575, wrote of a Mexican dish that combined seedless chipotles with beer: Chipotle Ale is based on Rogue\xc2\x92s Oregon Golden Ale, but delicately spiced with smoked chipotle chile peppers. Deep golden in color with a tight head, rich malty aroma, delicately smooth and crisp flavor, and subtle chipotle chili finish. Formerly known and packages as Mexicali Rogue, Chipotle Ale is created from Northwest Harrington, Klages, and Maier Munich Malts; Willamette and Cascade hops; and Smoked Jalapeno (Chipolte) Peppers. Chipotle Ale is targeted for spring release and available in a 22-ounce bottle and on draft. Blend it with Rogue Chocolate Stout and create a Mole\xc2\x92 black and tan',
                        'id': 19,
                        'name': 'Rogue Chipotle Ale',
                        'originalName': 'Rogue Chipotle Ale',
                        'rbScore': '62',
                        'rbUrl': u'http://www.ratebeer.com/beer/rogue-chipotle-ale/33254/',
                        'result': {u'Description': u'Chipotle Ale - Rogue Ales. Displayed for educational use only; do not reuse. Tweet. BA SCORE 81 good- ... 81 out of 100 based on 1,009 user ratings. Sign Up Now!',
                                   u'DisplayUrl': u'beeradvocate.com/beer/profile/132/354',
                                   u'ID': u'9901c84c-821b-428a-a597-4e4bf7cedf7f',
                                   u'Title': u'Chipotle Ale - Rogue Ales - Newport, OR - BeerAdvocate',
                                   u'Url': u'http://beeradvocate.com/beer/profile/132/354',
                                   u'__metadata': {u'type': u'WebResult',
                                                   u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Rogue Chipotle Ale "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                        'style': 'Spice/Herb/Vegetable'},
 'Rogue Mom Hefeweizen': {'abv': '5.2%',
                          'baScore': '??',
                          'baUrl': u'http://beeradvocate.com/beer/profile/132/41403',
                          'description': 'This Belgian-style blonde ale is an unfiltered fusion of wheat and barley malts, spiced with coriander and ginger.',
                          'id': 11,
                          'name': 'Rogue Half-E-Weizen (MoM Hefeweizen)',
                          'originalName': 'Rogue Mom Hefeweizen',
                          'rbScore': '62',
                          'rbUrl': u'http://www.ratebeer.com/beer/rogue-half-e-weizen-mom-hefeweizen/583/',
                          'result': {u'Description': u'Ratings for Mom Hefeweizen; style beer brewed by Rogue Ales in Newport, OR. N/A out of 100 with 0 BeerAdvocate opinions. ... N/A out of 100 based on 0 user ratings.',
                                     u'DisplayUrl': u'beeradvocate.com/beer/profile/132/41403',
                                     u'ID': u'30cf04f3-58da-4120-9716-9d5a7062bd2d',
                                     u'Title': u'Mom Hefeweizen - Rogue Ales - Newport, OR - BeerAdvocate',
                                     u'Url': u'http://beeradvocate.com/beer/profile/132/41403',
                                     u'__metadata': {u'type': u'WebResult',
                                                     u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Rogue Mom Hefeweizen "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                          'style': 'Wheat Ale'},
 'Southern Tier ': {'abv': '8%',
                    'baScore': u'91',
                    'baUrl': u'http://beeradvocate.com/beer/profile/3818/38394/?ba=HarmonMW',
                    'description': 'Brewed with 2 varieties of hops and 3 types of malts.\r\n\r\nABOUT THE BEER\r\nSTYLE: Double Uncommon\r\nBREWED SINCE: 2013\r\nABV: 8.0%\r\nFERMENTATION: Lager yeast at ale temperature, two varieties of hops, three varieties of malts \r\nCOLOR: Deep Gold\r\nEFFERVESCENCE: Light carbonation\r\nNOSE: Earthy, woody, slight mint aroma\r\nFLAVOR: Lightly toasted malts with woody and earthy hops, subtle but firm bitterness \r\nBITTERNESS: Low\r\nBODY: Low-medium\r\nSERVING TEMPERATURE: 40-45\xc2\xbaF\r\nGLASS: Nonic pint, mug\r\nAVAILABILITY: Spring-summer / 12oz (6pk and 24 bottle cases) / Draught\r\nCELLARING: 40-45\xc2\xbaF \r\n\r\nhttp://beerstreetjournal.com/new-southern-tier-2x-steam/',
                    'id': 17,
                    'name': 'Southern Tier 2x Steam Double Uncommon',
                    'originalName': 'Southern Tier ',
                    'rbScore': '68',
                    'rbUrl': u'http://www.ratebeer.com/beer/southern-tier-2x-steam-double-uncommon/207787/',
                    'result': {u'Description': u'Pumking - Southern Tier Brewing Company. Displayed for educational use only; do not reuse. Tweet. BA SCORE 91 ... 91 out of 100 based on 3,140 user ratings. Sign Up Now!',
                               u'DisplayUrl': u'beeradvocate.com/beer/profile/3818/38394/?ba=HarmonMW',
                               u'ID': u'4f261bc7-b5ec-4302-89aa-e0854c2b66f2',
                               u'Title': u'Pumking - Southern Tier Brewing Company - Lakewood, NY - BeerAdvocate',
                               u'Url': u'http://beeradvocate.com/beer/profile/3818/38394/?ba=HarmonMW',
                               u'__metadata': {u'type': u'WebResult',
                                               u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Southern Tier  "out of 100 based on" site:beeradvocate.com\'&$skip=1&$top=1'}},
                    'style': 'California Common'},
 'Southern Tier 2X Stout Nitro': {'abv': '7.5%',
                                  'baScore': u'85',
                                  'baUrl': u'http://beeradvocate.com/beer/profile/3818/76440',
                                  'description': 'Double Milk Stout',
                                  'id': 7,
                                  'name': 'Southern Tier 2X Stout',
                                  'originalName': 'Southern Tier 2X Stout Nitro',
                                  'rbScore': '95',
                                  'rbUrl': u'http://www.ratebeer.com/beer/southern-tier-2x-stout/161993/',
                                  'result': {u'Description': u'Overall, Southern Tier 2X Stout is a great milk stout. The stronger coffee flavors helps it stand out from the pack. ... 85 out of 100 based on 867 user ratings.',
                                             u'DisplayUrl': u'beeradvocate.com/beer/profile/3818/76440',
                                             u'ID': u'64cdd1cf-404a-4545-8cce-8a2094f151c2',
                                             u'Title': u'2X Stout - Southern Tier Brewing Company - Lakewood, NY - BeerAdvocate',
                                             u'Url': u'http://beeradvocate.com/beer/profile/3818/76440',
                                             u'__metadata': {u'type': u'WebResult',
                                                             u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Southern Tier 2X Stout Nitro "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                  'style': 'Sweet Stout'},
 'Southern Tier IPA': {'abv': '7.3%',
                       'baScore': u'87',
                       'baUrl': u'http://beeradvocate.com/beer/profile/3818/9088',
                       'description': 'IPA stands for India Pale Ale and ours is an American version of the classic style.  IPA\xc2\x92s namesake lies in its colonial roots.  British soldiers on their way to India dark a lot of beer, but found it would go stale on the long voyages.  Meanwhile, brewers knew that by adding more hops, the beer would stay fresh.  Voila',
                       'id': 23,
                       'name': 'Southern Tier IPA',
                       'originalName': 'Southern Tier IPA',
                       'rbScore': '96',
                       'rbUrl': u'http://www.ratebeer.com/beer/southern-tier-ipa/23004/',
                       'result': {u'Description': u'Ratings for IPA (India Pale Ale); American IPA style beer brewed by Southern Tier Brewing Company in Lakewood, NY. 87 out of 100 with 1460 BeerAdvocate opinions.',
                                  u'DisplayUrl': u'beeradvocate.com/beer/profile/3818/9088',
                                  u'ID': u'c038dafa-025d-4833-9756-4a293dc78f80',
                                  u'Title': u'IPA (India Pale Ale) - Southern Tier Brewing Company - Lakewood ...',
                                  u'Url': u'http://beeradvocate.com/beer/profile/3818/9088',
                                  u'__metadata': {u'type': u'WebResult',
                                                  u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Southern Tier IPA "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                       'style': 'India Pale Ale (IPA)'},
 'Starr Hill Northern Lights IPA': {'abv': '6.5%',
                                    'baScore': u'82',
                                    'baUrl': u'http://beeradvocate.com/beer/profile/13667/19922',
                                    'description': 'A classic American-style India Pale Ale, Northern Lights weighs in at 52 IBUs and 6.5% ABV. Characterized by its full-flavored bitterness and poignant citrus-floral aroma, a perfect blend of barley and hops make this a very balanced IPA. For the craftbrew connoisseur, Northern Lights is a deliciously crafted piece of the heavens.\r\n',
                                    'id': 29,
                                    'name': 'Starr Hill Northern Lights',
                                    'originalName': 'Starr Hill Northern Lights IPA',
                                    'rbScore': '83',
                                    'rbUrl': u'http://www.ratebeer.com/beer/starr-hill-northern-lights/93301/',
                                    'result': {u'Description': u'... American IPA style beer brewed by Starr Hill Brewery in Crozet, ... It smells like an old ipa. T - bitter grapefruit rind, light malty ... 82 out of 100 based on ...',
                                               u'DisplayUrl': u'beeradvocate.com/beer/profile/13667/19922',
                                               u'ID': u'48b97ff6-85b5-4fc3-aa6b-da515b449298',
                                               u'Title': u'Northern Lights IPA - Starr Hill Brewery - Crozet, VA - BeerAdvocate',
                                               u'Url': u'http://beeradvocate.com/beer/profile/13667/19922',
                                               u'__metadata': {u'type': u'WebResult',
                                                               u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Starr Hill Northern Lights IPA "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                    'style': 'India Pale Ale (IPA)'},
 'Troegs Dreamweaver Wheat Ale': {'abv': '4.8%',
                                  'baScore': u'85',
                                  'baUrl': u'http://beeradvocate.com/beer/profile/694/18305',
                                  'description': 'Long toasty days, cool breezy nights and a splash of magic provide the inspiration for the Troegs \r\nbrothers\xc2\x92 dreamiest Single Batch creation\xc2\x97Dreamweaver Wheat. Combining four wheat types with \r\nMunich and Pils malts, noble Saaz hops, and a yeast strain that imparts a spicy, peppery, clove taste \r\nwith a slight hint of bananas, Dreamweaver Wheat is an unfiltered blast of spicy, mouthwatering joy.',
                                  'id': 22,
                                  'name': 'Tr\xc3\xb6egs Dream Weaver Wheat',
                                  'originalName': 'Troegs Dreamweaver Wheat Ale',
                                  'rbScore': '84',
                                  'rbUrl': u'http://www.ratebeer.com/beer/troegs-dream-weaver-wheat/35827/',
                                  'result': {u'Description': u"Ratings for DreamWeaver Wheat; ... I haven't been much impressed by wheat beers to this point ... 85 out of 100 based on 1,092 user ratings.",
                                             u'DisplayUrl': u'beeradvocate.com/beer/profile/694/18305',
                                             u'ID': u'10e41179-b2bf-4d12-9ea1-0b7180890dee',
                                             u'Title': u'DreamWeaver Wheat - Tr\xf6egs Brewing Company - Hershey, PA ...',
                                             u'Url': u'http://beeradvocate.com/beer/profile/694/18305',
                                             u'__metadata': {u'type': u'WebResult',
                                                             u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Troegs Dreamweaver Wheat Ale "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                  'style': 'German Hefeweizen'},
 'Troegs Hop B ack Amber Ale': {'abv': '6%',
                                'baScore': u'90',
                                'baUrl': u'http://beeradvocate.com/beer/profile/694/6322',
                                'description': 'Troegs HopBack Amber gets its unique name and taste from the HopBack Vessel in our brewhouse. Packed full of whole flower hops, each batch circulates through the vessel, creating a fresh hoppy aroma, spicy taste and rich caramel note that defines this signature amber ale.   ',
                                'id': 21,
                                'name': 'Tr\xc3\xb6egs HopBack Amber Ale',
                                'originalName': 'Troegs Hop B ack Amber Ale',
                                'rbScore': '96',
                                'rbUrl': u'http://www.ratebeer.com/beer/troegs-hopback-amber-ale/17495/',
                                'result': {u'Description': u'Ratings for Tr\xf6egs Hopback Amber Ale; ... Head scales back to a nice thin layer on top of this brew. ... 90 out of 100 based on 1,825 user ratings.',
                                           u'DisplayUrl': u'beeradvocate.com/beer/profile/694/6322',
                                           u'ID': u'809141ed-12ea-4195-892e-670efa3d4066',
                                           u'Title': u'Tr\xf6egs Hopback Amber Ale - Tr\xf6egs Brewing Company - Hershey, PA ...',
                                           u'Url': u'http://beeradvocate.com/beer/profile/694/6322',
                                           u'__metadata': {u'type': u'WebResult',
                                                           u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Troegs Hop B ack Amber Ale "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                'style': 'Amber Ale'},
 'Troegs Sunshine Pilsner': {'abv': '4.7%',
                             'baScore': u'85',
                             'baUrl': u'http://beeradvocate.com/beer/profile/694/4108',
                             'description': 'Troegs Sunshine Pils is hand-crafted in our small brewery using only malted barley, noble hops and bottom-fermenting yeast.  This pilsner delivers a refreshing hop bitterness and a zesty, vibrant finish.  ',
                             'id': 20,
                             'name': 'Tr\xc3\xb6egs Sunshine Pils',
                             'originalName': 'Troegs Sunshine Pilsner',
                             'rbScore': '71',
                             'rbUrl': u'http://www.ratebeer.com/beer/troegs-sunshine-pils/14050/',
                             'result': {u'Description': u"Overall: I'm a big fan Troegs fan so that I enjoyed Sunshine Pils is of no surprise to me. ... 85 out of 100 based on 869 user ratings. Sign Up Now!",
                                        u'DisplayUrl': u'beeradvocate.com/beer/profile/694/4108',
                                        u'ID': u'c8a29211-39b0-47dc-8db8-c596f84bb300',
                                        u'Title': u'Tr\xf6egs Sunshine Pils - Tr\xf6egs Brewing Company - Hershey, PA ...',
                                        u'Url': u'http://beeradvocate.com/beer/profile/694/4108',
                                        u'__metadata': {u'type': u'WebResult',
                                                        u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Troegs Sunshine Pilsner "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                             'style': 'Pilsener'},
 'Unibroue Ephemere Belgium White': {'abv': '5.5%',
                                     'baScore': u'82',
                                     'baUrl': u'http://beeradvocate.com/beer/profile/22/3523',
                                     'description': '\xc3\x89ph\xc3\xa9m\xc3\xa8re is the third in a series of lively original-recipe beers that come and go before you know it. From season to season and year to year you\xc2\x92ll find a different \xc3\x89ph\xc3\xa9m\xc3\xa8re beer.',
                                     'id': 9,
                                     'name': 'Unibroue \xc3\x89ph\xc3\xa9m\xc3\xa8re Apple',
                                     'originalName': 'Unibroue Ephemere Belgium White',
                                     'rbScore': '83',
                                     'rbUrl': u'http://www.ratebeer.com/beer/unibroue-ephemere-apple/13558/',
                                     'result': {u'Description': u'Ratings for \xc9ph\xe9m\xe8re ... barley, malt, hops) from Belgium, but Unibroue has always done a great job with their beers. ... 82 out of 100 based on 1,394 user ratings.',
                                                u'DisplayUrl': u'beeradvocate.com/beer/profile/22/3523',
                                                u'ID': u'86d66a12-b200-410b-b0c9-9504fb21efe4',
                                                u'Title': u'\xc9ph\xe9m\xe8re (Apple) - Unibroue - Chambly, QC, Canada - BeerAdvocate',
                                                u'Url': u'http://beeradvocate.com/beer/profile/22/3523',
                                                u'__metadata': {u'type': u'WebResult',
                                                                u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Unibroue Ephemere Belgium White "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                     'style': 'Fruit Beer'},
 'Widmer Nelson Imperial': {'abv': '9.7%',
                            'baScore': u'89',
                            'baUrl': u'http://beeradvocate.com/beer/profile/8/67866',
                            'description': 'Brewed specially for the 2008 Oregon Brewers Festival',
                            'id': 5,
                            'name': 'Widmer Brothers Full Nelson IPA',
                            'originalName': 'Widmer Nelson Imperial',
                            'rbScore': '95',
                            'rbUrl': u'http://www.ratebeer.com/beer/widmer-brothers-full-nelson-ipa/90932/',
                            'result': {u'Description': u'Nelson Imperial IPA - Widmer Brothers Brewing Company. Displayed for educational use only; do not reuse. ... 89 out of 100 based on 409 user ratings. Sign Up Now!',
                                       u'DisplayUrl': u'beeradvocate.com/beer/profile/8/67866',
                                       u'ID': u'a6b67e99-9e6a-4383-904d-41dcef111af1',
                                       u'Title': u'Nelson Imperial IPA - Widmer Brothers Brewing Company - Portland ...',
                                       u'Url': u'http://beeradvocate.com/beer/profile/8/67866',
                                       u'__metadata': {u'type': u'WebResult',
                                                       u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Widmer Nelson Imperial "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                            'style': 'Imperial/Double IPA'}}
