beers = {'Achilles\xc2\xa0De Liter Van Pallieter': {'result': {u'Description': u'Ratings for De Liter Van Pallieter; ... Log in or Sign up. De Liter Van Pallieter - Microbrouwerij Achilles. ... N/A out of 100 based on 2 user ratings.',
                                                       u'DisplayUrl': u'beeradvocate.com/beer/profile/3442/58788',
                                                       u'ID': u'ab2292e4-2512-46b3-8ed5-bdc980d1220c',
                                                       u'Title': u'De Liter Van Pallieter - Microbrouwerij Achilles - Itegem, Belgium ...',
                                                       u'Url': u'http://beeradvocate.com/beer/profile/3442/58788',
                                                       u'__metadata': {u'type': u'WebResult',
                                                                       u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Achilles\xa0De Liter Van Pallieter "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                            'score': u'N/A'},
 'Aecht Schlenkerla\xc2\xa0Helles': {'result': {u'Description': u'Aecht Schlenkerla Helles Lagerbier from Brauerei Heller-Trum / Schlenkerla. 89 out of 100 based on 390 user ratings. Sign Up Now! Rate, Review & Track This Beer!',
                                                u'DisplayUrl': u'beeradvocate.com/beer/profile/263/29145',
                                                u'ID': u'6429fb75-cbae-4b1a-a687-3e847678e8c8',
                                                u'Title': u'Aecht Schlenkerla Helles Lagerbier - Brauerei Heller-Trum ...',
                                                u'Url': u'http://beeradvocate.com/beer/profile/263/29145',
                                                u'__metadata': {u'type': u'WebResult',
                                                                u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Aecht Schlenkerla\xa0Helles "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                     'score': u'89'},
 'Against The Grain/De Molen\xc2\xa0Bo & Luke': {'result': {u'Description': u'Against The Grain / De Molen Bo & Luke from Against The Grain Brewery & Smokehouse. 94 out of 100 based on 47 user ratings. Sign Up Now! Rate, Review & Track This Beer!',
                                                            u'DisplayUrl': u'beeradvocate.com/beer/profile/26850/85986/?ba=EgadBananas',
                                                            u'ID': u'22426221-470a-439a-880a-d6c0202257e2',
                                                            u'Title': u'Against The Grain / De Molen Bo & Luke - Against The Grain Brewery ...',
                                                            u'Url': u'http://beeradvocate.com/beer/profile/26850/85986/?ba=EgadBananas',
                                                            u'__metadata': {u'type': u'WebResult',
                                                                            u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Against The Grain/De Molen\xa0Bo & Luke "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                                 'score': u'94'},
 'Against The Grain\xc2\xa02 Wheel Death Machine': {'result': {u'Description': u'Ratings for Two Wheel Death Machine; ... Two Wheel Death Machine - Against The Grain Brewery & Smokehouse. ... N/A out of 100 based on 1 user ratings.',
                                                               u'DisplayUrl': u'beeradvocate.com/beer/profile/26850/89365/?ba=TMoney2591',
                                                               u'ID': u'5587fb72-4a85-4468-b554-557f9491daf6',
                                                               u'Title': u'Two Wheel Death Machine - Against The Grain Brewery & Smokehouse ...',
                                                               u'Url': u'http://beeradvocate.com/beer/profile/26850/89365/?ba=TMoney2591',
                                                               u'__metadata': {u'type': u'WebResult',
                                                                               u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Against The Grain\xa02 Wheel Death Machine "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                                    'score': u'N/A'},
 'Against The Grain\xc2\xa0Galangal Action': {'result': {u'Description': u'Galangal Action - Against The Grain Brewery & Smokehouse. No picture uploaded. Have one? Upload it now. Tweet. BA SCORE ... N/A out of 100 based on 4 user ratings.',
                                                         u'DisplayUrl': u'beeradvocate.com/beer/profile/26850/85990',
                                                         u'ID': u'c6c8e852-8b1d-4699-9b9e-652abd9efe59',
                                                         u'Title': u'Galangal Action - Against The Grain Brewery & Smokehouse ...',
                                                         u'Url': u'http://beeradvocate.com/beer/profile/26850/85990',
                                                         u'__metadata': {u'type': u'WebResult',
                                                                         u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Against The Grain\xa0Galangal Action "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                              'score': u'N/A'},
 'Against The Grain\xc2\xa0Shit Jeans': {'result': {u'Description': u'No shit ... ever. ..." and ... DaButt from Against The Grain Brewery & Smokehouse. N/A out of 100 based on 2 user ratings. Sign Up Now! Rate, Review & Track This Beer!',
                                                    u'DisplayUrl': u'beeradvocate.com/beer/profile/26850/89613/?ba=BEERchitect',
                                                    u'ID': u'abfd8fdb-7c74-4fd3-9963-e536a3db1cc5',
                                                    u'Title': u'DaButt - Against The Grain Brewery & Smokehouse - Louisville, KY ...',
                                                    u'Url': u'http://beeradvocate.com/beer/profile/26850/89613/?ba=BEERchitect',
                                                    u'__metadata': {u'type': u'WebResult',
                                                                    u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Against The Grain\xa0Shit Jeans "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                         'score': u'N/A'},
 'Allagash\xc2\xa0Grand Cru': {'result': {u'Description': u'Allagash Grand Cru - Allagash Brewing Company. Displayed for educational use only; do not reuse. Tweet. ... 92 out of 100 based on 527 user ratings. Sign Up Now!',
                                          u'DisplayUrl': u'beeradvocate.com/beer/profile/4/58/?ba=Thomas_Picton',
                                          u'ID': u'2a5d78b0-ea32-4477-942a-14e06c020954',
                                          u'Title': u'Allagash Grand Cru - Allagash Brewing Company - Portland, ME ...',
                                          u'Url': u'http://beeradvocate.com/beer/profile/4/58/?ba=Thomas_Picton',
                                          u'__metadata': {u'type': u'WebResult',
                                                          u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Allagash\xa0Grand Cru "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                               'score': u'92'},
 'Allagash\xc2\xa0White': {'result': {u'Description': u'Ratings for Allagash White; Witbier style beer brewed by Allagash Brewing Company in Portland, ... 93 out of 100 based on 2,245 user ratings. Sign Up Now!',
                                      u'DisplayUrl': u'beeradvocate.com/beer/profile/4/59/?ba=mess41',
                                      u'ID': u'd554a95b-2416-4334-9e0f-ef5a8a753b97',
                                      u'Title': u'Allagash White - Allagash Brewing Company - Portland, ME ...',
                                      u'Url': u'http://beeradvocate.com/beer/profile/4/59/?ba=mess41',
                                      u'__metadata': {u'type': u'WebResult',
                                                      u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Allagash\xa0White "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                           'score': u'93'},
 'Alvinne\xc2\xa0Gaspar': {'result': {u'Description': u'Gaspar Ale - Picobrouwerij Alvinne / Den Bierzolder. Displayed for educational use only; do not reuse. ... 82 out of 100 based on 119 user ratings. Sign Up Now!',
                                      u'DisplayUrl': u'beeradvocate.com/beer/profile/6288/37540',
                                      u'ID': u'11edc2a1-4f5e-4374-a6df-dd5fbc092c52',
                                      u'Title': u'Gaspar Ale - Picobrouwerij Alvinne / Den Bierzolder - Heule ...',
                                      u'Url': u'http://beeradvocate.com/beer/profile/6288/37540',
                                      u'__metadata': {u'type': u'WebResult',
                                                      u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Alvinne\xa0Gaspar "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                           'score': u'82'},
 'Alvinne\xc2\xa0Melchior': {'result': {u'Description': u'Melchior - Picobrouwerij Alvinne / Den Bierzolder. Displayed for educational use only; do not reuse. Tweet. ... 82 out of 100 based on 72 user ratings. Sign Up Now!',
                                        u'DisplayUrl': u'beeradvocate.com/beer/profile/6288/27188',
                                        u'ID': u'd9fe164a-d2bb-48df-bb2d-d7f2895ea31f',
                                        u'Title': u'Melchior - Picobrouwerij Alvinne / Den Bierzolder - Heule, Belgium ...',
                                        u'Url': u'http://beeradvocate.com/beer/profile/6288/27188',
                                        u'__metadata': {u'type': u'WebResult',
                                                        u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Alvinne\xa0Melchior "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                             'score': u'82'},
 'Ballast Point\xc2\xa0Victory At Sea': {'result': {u'Description': u'Ratings for Victory At Sea Coffee Vanilla Imperial Porter; American Porter style beer brewed by Ballast Point Brewing Company in ... 97 out of 100 based on 1,503 user ...',
                                                    u'DisplayUrl': u'beeradvocate.com/beer/profile/199/48505',
                                                    u'ID': u'46a73d49-011a-4ba1-ac4d-2d44f7660221',
                                                    u'Title': u'Victory At Sea Coffee Vanilla Imperial Porter - Ballast Point ...',
                                                    u'Url': u'http://beeradvocate.com/beer/profile/199/48505',
                                                    u'__metadata': {u'type': u'WebResult',
                                                                    u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Ballast Point\xa0Victory At Sea "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                         'score': u'97'},
 'Belhaven\xc2\xa0Black (Nitro)': {'result': {u'Description': u'Ratings for Belhaven Scottish Ale; ... Nitro can scared the kitties and me too.. ... 86 out of 100 based on 1,093 user ratings.',
                                              u'DisplayUrl': u'beeradvocate.com/beer/profile/148/1163/?ba=JohnGalt1',
                                              u'ID': u'84e2b0e4-35a8-4742-9e3b-c7e24ac20197',
                                              u'Title': u'Belhaven Scottish Ale - Belhaven Brewery Company Ltd. - Dunbar ...',
                                              u'Url': u'http://beeradvocate.com/beer/profile/148/1163/?ba=JohnGalt1',
                                              u'__metadata': {u'type': u'WebResult',
                                                              u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Belhaven\xa0Black (Nitro) "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                   'score': u'86'},
 'Blue Moon\xc2\xa0White': {'result': {u'Description': u'Served cold Blue Moon Belgian White in a glass with an orange slice at my favorite local mom & pop pizza restaurant. ... 78 out of 100 based on 3,101 user ratings.',
                                       u'DisplayUrl': u'beeradvocate.com/beer/profile/306/1212',
                                       u'ID': u'ba6026cb-0a5a-445e-9f60-f1fa2c8e2fa1',
                                       u'Title': u'Blue Moon Belgian White - Coors Brewing Company - Golden, CO ...',
                                       u'Url': u'http://beeradvocate.com/beer/profile/306/1212',
                                       u'__metadata': {u'type': u'WebResult',
                                                       u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Blue Moon\xa0White "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                            'score': u'78'},
 'Blue Mountain \xc2\xa0Barrel Aged Dirty Belgian': {'result': {u'Description': u"... Blue Mountain Barrel House has the best Virginia beers I've tasted yet. ... 86 out of 100 based on 63 user ratings. ... (Bourbon Barrel Aged) (De Struise Brouwers)",
                                                                u'DisplayUrl': u'beeradvocate.com/beer/profile/16352/82463',
                                                                u'ID': u'aef2f0c2-b04c-431b-afae-30694be486af',
                                                                u'Title': u'Local Species - Blue Mountain Brewery - Afton, VA - BeerAdvocate',
                                                                u'Url': u'http://beeradvocate.com/beer/profile/16352/82463',
                                                                u'__metadata': {u'type': u'WebResult',
                                                                                u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Blue Mountain \xa0Barrel Aged Dirty Belgian "out of 100 based on" site:beeradvocate.com\'&$skip=1&$top=1'}},
                                                     'score': u'86'},
 'Blue Mountain \xc2\xa0Mandolin': {'result': {u'Description': u'Blue Mountain Mandolin is slick, fruity, syrupy, and sticky. ... 86 out of 100 based on 43 user ratings. Sign Up Now! Rate, Review & Track This Beer!',
                                               u'DisplayUrl': u'beeradvocate.com/beer/profile/16352/42005',
                                               u'ID': u'a9ca3aca-3512-45f7-acfd-653aff1614ca',
                                               u'Title': u'Mandolin - Blue Mountain Brewery - Afton, VA - BeerAdvocate',
                                               u'Url': u'http://beeradvocate.com/beer/profile/16352/42005',
                                               u'__metadata': {u'type': u'WebResult',
                                                               u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Blue Mountain \xa0Mandolin "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                    'score': u'86'},
 'Brewers Art\xc2\xa0Resurrection': {'result': {u'Description': u"Ratings for Brewer's Art Resurrection; Dubbel style beer brewed by The Brewer's Art in Baltimore, ... 87 out of 100 based on 211 user ratings. Sign Up Now!",
                                                u'DisplayUrl': u'beeradvocate.com/beer/profile/997/7097/?ba=countmeoutt',
                                                u'ID': u'3c3e9179-2709-4208-ba34-defaf907f7b4',
                                                u'Title': u"Brewer's Art Resurrection - The Brewer's Art - Baltimore, MD ...",
                                                u'Url': u'http://beeradvocate.com/beer/profile/997/7097/?ba=countmeoutt',
                                                u'__metadata': {u'type': u'WebResult',
                                                                u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Brewers Art\xa0Resurrection "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                     'score': u'87'},
 'Burley Oak\xc2\xa0Hopless Beach': {'result': {u'Description': u'Hopless Beach - Burley Oak Brewery. No picture uploaded. Have one? Upload it now. Tweet. BA SCORE N/A-2 Ratings: ... N/A out of 100 based on 2 user ratings. Sign Up Now!',
                                                u'DisplayUrl': u'beeradvocate.com/beer/profile/26749/88910',
                                                u'ID': u'29a6ac5e-e04c-4cdd-9c77-ddeab2422978',
                                                u'Title': u'Hopless Beach - Burley Oak Brewery - Berlin, MD - BeerAdvocate',
                                                u'Url': u'http://beeradvocate.com/beer/profile/26749/88910',
                                                u'__metadata': {u'type': u'WebResult',
                                                                u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Burley Oak\xa0Hopless Beach "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                     'score': u'N/A'},
 'Burley Oak\xc2\xa0Rude Girl': {'result': {u'Description': u'Barrel Aged Rude Boy - Burley Oak Brewery. No picture uploaded. Have one? Upload it now. Tweet. BA SCORE N/A- ... N/A out of 100 based on 0 user ratings. Sign Up Now!',
                                            u'DisplayUrl': u'beeradvocate.com/beer/profile/26749/88907',
                                            u'ID': u'cb7364d0-84c3-47d1-ae0b-cac8d928d701',
                                            u'Title': u'Barrel Aged Rude Boy - Burley Oak Brewery - Berlin, MD - BeerAdvocate',
                                            u'Url': u'http://beeradvocate.com/beer/profile/26749/88907',
                                            u'__metadata': {u'type': u'WebResult',
                                                            u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Burley Oak\xa0Rude Girl "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                 'score': u'N/A'},
 'CCM\xc2\xa0Montseny Blat': {'result': '', 'score': 'N/A'},
 'Chimay\xc2\xa0Cinq Cents': {'result': {u'Description': u'Labeled Chimay Cinq Cents in 750ml bottle. View: Beers (5) | Events (0) ... 92 out of 100 based on 2,413 user ratings. Sign Up Now! Rate, Review & Track This Beer!',
                                         u'DisplayUrl': u'beeradvocate.com/beer/profile/215/1346',
                                         u'ID': u'198a758f-a435-4808-bc84-2fef8af89060',
                                         u'Title': u'Chimay Tripel (White) - Bi\xe8res de Chimay S.A. - Baileux (Chimay ...',
                                         u'Url': u'http://beeradvocate.com/beer/profile/215/1346',
                                         u'__metadata': {u'type': u'WebResult',
                                                         u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Chimay\xa0Cinq Cents "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                              'score': u'92'},
 'Contreras Valeir\xc2\xa0Extra': {'result': {u'Description': u'Valeir Extra - Brouwerij Contreras. Displayed for educational use only; do not reuse. Tweet. BA SCORE 87 good- ... 87 out of 100 based on 55 user ratings. Sign Up Now!',
                                              u'DisplayUrl': u'beeradvocate.com/beer/profile/3463/50435',
                                              u'ID': u'e72ed313-1eb9-455a-a388-15826369bd62',
                                              u'Title': u'Valeir Extra - Brouwerij Contreras - Gavere, Belgium - BeerAdvocate',
                                              u'Url': u'http://beeradvocate.com/beer/profile/3463/50435',
                                              u'__metadata': {u'type': u'WebResult',
                                                              u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Contreras Valeir\xa0Extra "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                   'score': u'87'},
 'Crispin\xc2\xa0Cider': {'result': {u'Description': u'A- Wow, this pours more colorless than the Crispin cider I had last night. Very pale straw color with a slight haze. ... 83 out of 100 based on 59 user ratings.',
                                     u'DisplayUrl': u'beeradvocate.com/beer/profile/11361/26554',
                                     u'ID': u'7a4dea17-8e6f-45c8-80f3-d09c28361fb7',
                                     u'Title': u'K\xf6lsch - Heiner Brau - Covington, LA - BeerAdvocate',
                                     u'Url': u'http://beeradvocate.com/beer/profile/11361/26554',
                                     u'__metadata': {u'type': u'WebResult',
                                                     u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Crispin\xa0Cider "out of 100 based on" site:beeradvocate.com\'&$skip=2&$top=1'}},
                          'score': u'83'},
 'De Dolle\xc2\xa0Arabier': {'result': {u'Description': u'Ratings for De Dolle Arabier; Belgian Strong Pale Ale style beer brewed by Brouwerij De Dolle Brouwers in Esen, ... 91 out of 100 based on 368 user ratings.',
                                        u'DisplayUrl': u'beeradvocate.com/beer/profile/201/633',
                                        u'ID': u'6d225278-39eb-4552-a800-6779bca5e9d3',
                                        u'Title': u'De Dolle Arabier - Brouwerij De Dolle Brouwers - Esen, Belgium ...',
                                        u'Url': u'http://beeradvocate.com/beer/profile/201/633',
                                        u'__metadata': {u'type': u'WebResult',
                                                        u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'De Dolle\xa0Arabier "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                             'score': u'91'},
 'De Glazen Toren\xc2\xa0Saison De Epre Mere': {'result': {u'Description': u"Ratings for Saison D'Erpe-Mere; Saison / Farmhouse Ale style beer brewed by KleinBrouwerij De Glazen Toren in Erpe-Mere, ... 92 out of 100 based on 223 user ratings.",
                                                           u'DisplayUrl': u'beeradvocate.com/beer/profile/10557/21113',
                                                           u'ID': u'6381d559-5f81-412e-9785-f47ddcaf2d9c',
                                                           u'Title': u"Saison D'Erpe-Mere - KleinBrouwerij De Glazen Toren - Erpe-Mere ...",
                                                           u'Url': u'http://beeradvocate.com/beer/profile/10557/21113',
                                                           u'__metadata': {u'type': u'WebResult',
                                                                           u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'De Glazen Toren\xa0Saison De Epre Mere "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                                'score': u'92'},
 'De La Senne\xc2\xa0Band of Brothers': {'result': {u'Description': u'Ratings for Band Of Brothers S01E01; Belgian Pale Ale style beer brewed by Brasserie de la Senne in Brussels, ... 86 out of 100 based on 20 user ratings.',
                                                    u'DisplayUrl': u'beeradvocate.com/beer/profile/16320/81303/?ba=WindedIndian',
                                                    u'ID': u'ab9a82b6-97b1-489a-ac18-65a9d093ae93',
                                                    u'Title': u'Band Of Brothers S01E01 - Brasserie de la Senne - Brussels ...',
                                                    u'Url': u'http://beeradvocate.com/beer/profile/16320/81303/?ba=WindedIndian',
                                                    u'__metadata': {u'type': u'WebResult',
                                                                    u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'De La Senne\xa0Band of Brothers "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                         'score': u'86'},
 'De Landtsheer\xc2\xa0Malhuer 10': {'result': {u'Description': u'Malheur 10\xb0 - Brouwerij De Landtsheer NV. Displayed for educational use only; do not reuse. Tweet. BA SCORE 89 ... 89 out of 100 based on 267 user ratings. Sign Up Now!',
                                                u'DisplayUrl': u'beeradvocate.com/beer/profile/669/6118',
                                                u'ID': u'ff3846c2-22ba-4435-be58-cd2474b20474',
                                                u'Title': u'Malheur 10\xb0 - Brouwerij De Landtsheer NV - Buggenhout, Belgium ...',
                                                u'Url': u'http://beeradvocate.com/beer/profile/669/6118',
                                                u'__metadata': {u'type': u'WebResult',
                                                                u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'De Landtsheer\xa0Malhuer 10 "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                     'score': u'89'},
 'De Le Senne\xc2\xa0Zwarte Piet': {'result': {u'Description': u'Equinox / Zwarte Piet (2012- ) - Brasserie de la Senne. Displayed for educational use only; do not reuse. Tweet. BA SCORE 85 ... 85 out of 100 based on 62 user ratings.',
                                               u'DisplayUrl': u'beeradvocate.com/beer/profile/16320/38708/?ba=GRUUMSH',
                                               u'ID': u'c921cc9a-0bc6-4298-9489-5ad48761fe77',
                                               u'Title': u'Equinox / Zwarte Piet (2012- ) - Brasserie de la Senne - Brussels ...',
                                               u'Url': u'http://beeradvocate.com/beer/profile/16320/38708/?ba=GRUUMSH',
                                               u'__metadata': {u'type': u'WebResult',
                                                               u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'De Le Senne\xa0Zwarte Piet "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                    'score': u'85'},
 'Delirium\xc2\xa0Tremens': {'result': {u'Description': u'Delirium Tremens - Brouwerij Huyghe. Displayed for educational use only; do not reuse. Tweet. ... 92 out of 100 based on 2,684 user ratings. Sign Up Now!',
                                        u'DisplayUrl': u'beeradvocate.com/beer/profile/180/1385/?ba=vkv822',
                                        u'ID': u'a364e435-a311-463d-96be-76ad949d5c51',
                                        u'Title': u'Delirium Tremens - Brouwerij Huyghe - Melle, Belgium - BeerAdvocate',
                                        u'Url': u'http://beeradvocate.com/beer/profile/180/1385/?ba=vkv822',
                                        u'__metadata': {u'type': u'WebResult',
                                                        u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Delirium\xa0Tremens "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                             'score': u'92'},
 'Dilweyns\xc2\xa0Vicaris Triple Gueuze': {'result': {u'Description': u'Labeled Vicaris Tripel-Gueuze. ... The woven Vicaris Triple and Giradin Geuze create a wonderment of flavors that both temper ... 82 out of 100 based on 40 user ...',
                                                      u'DisplayUrl': u'beeradvocate.com/beer/profile/21734/38214',
                                                      u'ID': u'f58b0687-b1e3-4c5d-9991-75bbcd21527e',
                                                      u'Title': u'Vicardin - Brouwerij Dilewyns - Grembergen, Belgium - BeerAdvocate',
                                                      u'Url': u'http://beeradvocate.com/beer/profile/21734/38214',
                                                      u'__metadata': {u'type': u'WebResult',
                                                                      u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Dilweyns\xa0Vicaris Triple Gueuze "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                           'score': u'82'},
 'Dogfish Head\xc2\xa0Rhizing Bines': {'result': {u'Description': u'Dogfish Head Rhizing Bines is floral, metallic, and bubbly. ... 84 out of 100 based on 118 user ratings. Sign Up Now! Rate, Review & Track This Beer!',
                                                  u'DisplayUrl': u'beeradvocate.com/beer/profile/10099/89024',
                                                  u'ID': u'a471a301-6b31-4dc2-be55-8f6be61e09b0',
                                                  u'Title': u'Rhizing Bines - Dogfish Head Brewery - Milton, DE - BeerAdvocate',
                                                  u'Url': u'http://beeradvocate.com/beer/profile/10099/89024',
                                                  u'__metadata': {u'type': u'WebResult',
                                                                  u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Dogfish Head\xa0Rhizing Bines "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                       'score': u'84'},
 'Dominion\xc2\xa0Oak Barrel Stout(Nitro)': {'result': {u'Description': u'Dominion Oak Barrel Stout - Old Dominion Brewing Company. ... (86), nitro-tap (10), growler (3). ... 89 out of 100 based on 872 user ratings.',
                                                        u'DisplayUrl': u'beeradvocate.com/beer/profile/402/1192',
                                                        u'ID': u'5d557577-24d9-4f3b-bf2a-e67637e86a14',
                                                        u'Title': u'Dominion Oak Barrel Stout - Old Dominion Brewing Company - Dover ...',
                                                        u'Url': u'http://beeradvocate.com/beer/profile/402/1192',
                                                        u'__metadata': {u'type': u'WebResult',
                                                                        u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Dominion\xa0Oak Barrel Stout(Nitro) "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                             'score': u'89'},
 'Elysian\xc2\xa0Mortis': {'result': {u'Description': u'Mortis - Elysian Brewing Company. Displayed for educational use only; do not reuse. Tweet. BA SCORE 78 ... 78 out of 100 based on 19 user ratings. Sign Up Now!',
                                      u'DisplayUrl': u'beeradvocate.com/beer/profile/700/87328',
                                      u'ID': u'b62d3849-cd97-4861-a930-3e508fc818c2',
                                      u'Title': u'Mortis - Elysian Brewing Company - Seattle, WA - BeerAdvocate',
                                      u'Url': u'http://beeradvocate.com/beer/profile/700/87328',
                                      u'__metadata': {u'type': u'WebResult',
                                                      u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Elysian\xa0Mortis "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                           'score': u'78'},
 'Emelisse\xc2\xa0Black & Tan Arbeg': {'result': {u'Description': u'Ratings for Emelisse Espresso Stout; ... Black body with just a dusting of tan head & some floaties. ... 82 out of 100 based on 91 user ratings.',
                                                  u'DisplayUrl': u'beeradvocate.com/beer/profile/11890/55742',
                                                  u'ID': u'e7019035-fc06-4e42-bfaf-36cddd6b7bde',
                                                  u'Title': u'Emelisse Espresso Stout - Bierbrouwerij Grand-Caf\xe9 Emelisse ...',
                                                  u'Url': u'http://beeradvocate.com/beer/profile/11890/55742',
                                                  u'__metadata': {u'type': u'WebResult',
                                                                  u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Emelisse\xa0Black & Tan Arbeg "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                       'score': u'82'},
 'Emelisse\xc2\xa0Milk Stout': {'result': {u'Description': u'Ratings for Emelisse Espresso Stout; ... Coffee and milk chocolate flavors hit the tastebuds pretty much at the same time. ... 82 out of 100 based on 91 user ratings.',
                                           u'DisplayUrl': u'beeradvocate.com/beer/profile/11890/55742',
                                           u'ID': u'845fab94-9a05-40db-b0a7-5924024c7eb0',
                                           u'Title': u'Emelisse Espresso Stout - Bierbrouwerij Grand-Caf\xe9 Emelisse ...',
                                           u'Url': u'http://beeradvocate.com/beer/profile/11890/55742',
                                           u'__metadata': {u'type': u'WebResult',
                                                           u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Emelisse\xa0Milk Stout "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                'score': u'82'},
 'Firestone Walker\xc2\xa0Sucaba': {'result': {u'Description': u'... English Barleywine style beer brewed by Firestone Walker Brewing Co. in ... Sucaba pours a Ron-Burgundy-laced black with ... 100 out of 100 based on 1,423 user ...',
                                               u'DisplayUrl': u'beeradvocate.com/beer/profile/2210/41121',
                                               u'ID': u'eb173a4c-c10e-48fe-a07e-3e35e44213b9',
                                               u'Title': u'\xa7ucaba (Abacus) - Firestone Walker Brewing Co. - Paso Robles, CA ...',
                                               u'Url': u'http://beeradvocate.com/beer/profile/2210/41121',
                                               u'__metadata': {u'type': u'WebResult',
                                                               u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Firestone Walker\xa0Sucaba "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                    'score': u'100'},
 'Firestone Walker\xc2\xa0Walkers Reserve': {'result': {u'Description': u'Firestone Walker Walker\u2019s Reserve Appearance: Firestone\u2019s year-round porter offering pours a dark brown, ... 87 out of 100 based on 985 user ratings. Sign Up Now!',
                                                        u'DisplayUrl': u'beeradvocate.com/beer/profile/2210/6371',
                                                        u'ID': u'2767c505-eab3-4f21-85b6-84be537516fb',
                                                        u'Title': u"Walker's Reserve - Porter - Firestone Walker Brewing Co. - Paso ...",
                                                        u'Url': u'http://beeradvocate.com/beer/profile/2210/6371',
                                                        u'__metadata': {u'type': u'WebResult',
                                                                        u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Firestone Walker\xa0Walkers Reserve "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                             'score': u'87'},
 'Firestone Walker\xc2\xa0XVI 16th Anniversary': {'result': {u'Description': u'Firestone 16 - Anniversary Ale - Firestone Walker Brewing Co. Displayed for educational use only; do not reuse. Tweet. ... 95 out of 100 based on 316 user ratings.',
                                                             u'DisplayUrl': u'beeradvocate.com/beer/profile/2210/87151',
                                                             u'ID': u'ef988c8a-83fd-4387-a71b-33a8138c0488',
                                                             u'Title': u'Firestone 16 - Anniversary Ale - Firestone Walker Brewing Co ...',
                                                             u'Url': u'http://beeradvocate.com/beer/profile/2210/87151',
                                                             u'__metadata': {u'type': u'WebResult',
                                                                             u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Firestone Walker\xa0XVI 16th Anniversary "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                                  'score': u'95'},
 'Flying Dog\xc2\xa0Double Dog (Nitro)': {'result': {u'Description': u"Tight nitro bubbles. Pleasant. 'Double Pale Ales' must not be my thing. ... Double Dog Double Pale Ale from Flying Dog Brewery. 89 out of 100 based on 1,218 user ratings.",
                                                     u'DisplayUrl': u'beeradvocate.com/beer/profile/68/35754',
                                                     u'ID': u'3dd048cd-ed96-4aa4-8d1e-5e579bea306c',
                                                     u'Title': u'Double Dog Double Pale Ale - Flying Dog Brewery - Frederick, MD ...',
                                                     u'Url': u'http://beeradvocate.com/beer/profile/68/35754',
                                                     u'__metadata': {u'type': u'WebResult',
                                                                     u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Flying Dog\xa0Double Dog (Nitro) "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                          'score': u'89'},
 'Fruli\xc2\xa0Strawberry': {'result': {u'Description': u'Ratings for Van Diest Fr\xfcli Strawberry Beer; ... and fruli is a good example of both. ... 78 out of 100 based on 234 user ratings.',
                                        u'DisplayUrl': u'beeradvocate.com/beer/profile/180/12738',
                                        u'ID': u'b1b437e4-1c21-4ab0-9bf5-8d9fd5d786a8',
                                        u'Title': u'Van Diest Fr\xfcli Strawberry Beer - Brouwerij Huyghe - Melle ...',
                                        u'Url': u'http://beeradvocate.com/beer/profile/180/12738',
                                        u'__metadata': {u'type': u'WebResult',
                                                        u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Fruli\xa0Strawberry "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                             'score': u'78'},
 'Guinness\xc2\xa0Stout': {'result': {u'Description': u'Ratings for Guinness Extra Stout (Original); Irish Dry Stout style beer brewed by Guinness Ltd. in Dublin, ... 84 out of 100 based on 2,080 user ratings.',
                                      u'DisplayUrl': u'beeradvocate.com/beer/profile/209/650',
                                      u'ID': u'06c78036-5be2-42c2-9175-74a61063e3f7',
                                      u'Title': u'Guinness Extra Stout (Original) - Guinness Ltd. - Dublin, Ireland ...',
                                      u'Url': u'http://beeradvocate.com/beer/profile/209/650',
                                      u'__metadata': {u'type': u'WebResult',
                                                      u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Guinness\xa0Stout "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                           'score': u'84'},
 'Harpoon\xc2\xa0UFO Raspberry': {'result': {u'Description': u'UFO Raspberry Hefeweizen - Harpoon Brewery & Beer Hall. Displayed for educational use only; do not reuse. ... 81 out of 100 based on 408 user ratings. Sign Up Now!',
                                             u'DisplayUrl': u'beeradvocate.com/beer/profile/98/28672',
                                             u'ID': u'6b55646b-ffab-4a19-8327-692f6c83b6ca',
                                             u'Title': u'UFO Raspberry Hefeweizen - Harpoon Brewery & Beer Hall - Boston ...',
                                             u'Url': u'http://beeradvocate.com/beer/profile/98/28672/',
                                             u'__metadata': {u'type': u'WebResult',
                                                             u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Harpoon\xa0UFO Raspberry "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                  'score': u'81'},
 'Heavy Seas\xc2\xa0Loose Cannon': {'result': {u'Description': u'Heavy Seas Loose Cannon - American Hop3 Ale - Heavy Seas Beer. Displayed for educational use only; do not reuse. ... 91 out of 100 based on 1,807 user ratings.',
                                               u'DisplayUrl': u'beeradvocate.com/beer/profile/898/25755',
                                               u'ID': u'3be47e91-e5dd-4836-85f5-d0d99202055b',
                                               u'Title': u'Heavy Seas Loose Cannon - American Hop3 Ale - Heavy Seas Beer ...',
                                               u'Url': u'http://beeradvocate.com/beer/profile/898/25755',
                                               u'__metadata': {u'type': u'WebResult',
                                                               u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Heavy Seas\xa0Loose Cannon "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                    'score': u'91'},
 'Het Nest\xc2\xa0Schuppenboer': {'result': {u'Description': u'Jack Of Spades / Schuppenboer Tripel - Hobbybrouwerij Het Nest. No picture uploaded. Have one? Upload it now. ... N/A out of 100 based on 1 user ratings. Sign Up Now!',
                                             u'DisplayUrl': u'beeradvocate.com/beer/profile/29672/84155',
                                             u'ID': u'868d4861-fed0-4a7a-8ec6-45da7c2dd00a',
                                             u'Title': u'Jack Of Spades / Schuppenboer Tripel - Hobbybrouwerij Het Nest ...',
                                             u'Url': u'http://beeradvocate.com/beer/profile/29672/84155',
                                             u'__metadata': {u'type': u'WebResult',
                                                             u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Het Nest\xa0Schuppenboer "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                  'score': u'N/A'},
 'Hof Ten Dormaal\xc2\xa0BA Series Armagnac': {'result': {u'Description': u'BA SCORE 85 good- 13 Ratings: THE BROS N ... Armagnac from Brouwerij Hof Ten Dormaal. 85 out of 100 based on 13 user ratings. Sign Up Now! Rate, Review & Track This Beer!',
                                                          u'DisplayUrl': u'beeradvocate.com/beer/profile/23031/84099/?ba=mcphish22',
                                                          u'ID': u'dd3f72c5-7299-4af1-9888-8aa84da74cb3',
                                                          u'Title': u'Barrel-Aged Project Brew No. 4 - Armagnac - Brouwerij Hof Ten Dormaal',
                                                          u'Url': u'http://beeradvocate.com/beer/profile/23031/84099/?ba=mcphish22',
                                                          u'__metadata': {u'type': u'WebResult',
                                                                          u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Hof Ten Dormaal\xa0BA Series Armagnac "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                               'score': u'85'},
 'Hofbrau\xc2\xa0Hefeweizen': {'result': {u'Description': u'A liter of hefeweizen in a biergarden in the summer is a treat. ... 84 out of 100 based on 29 user ratings. Sign Up Now! Rate, Review & Track This Beer!',
                                          u'DisplayUrl': u'beeradvocate.com/beer/profile/4685/19331',
                                          u'ID': u'3964a7b3-ef7d-4784-8e1e-8083d0f62fbd',
                                          u'Title': u'Hofbr\xe4u Munich Weizen - Hofbr\xe4uhaus Newport - Newport, KY ...',
                                          u'Url': u'http://beeradvocate.com/beer/profile/4685/19331',
                                          u'__metadata': {u'type': u'WebResult',
                                                          u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Hofbrau\xa0Hefeweizen "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                               'score': u'84'},
 'Leifmans\xc2\xa0Goudenband': {'result': {u'Description': u'Brouwerij Liefmans Goudenband is an excellent example of a Flanders Ode Bruin. ... 93 out of 100 based on 719 user ratings. Sign Up Now! Rate, Review & Track This Beer!',
                                           u'DisplayUrl': u'beeradvocate.com/beer/profile/283/773',
                                           u'ID': u'bad92ec6-0148-447d-9303-c9ca06d3c16a',
                                           u'Title': u'Goudenband - Brouwerij Liefmans - Oudenaarde, Belgium - BeerAdvocate',
                                           u'Url': u'http://beeradvocate.com/beer/profile/283/773',
                                           u'__metadata': {u'type': u'WebResult',
                                                           u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Leifmans\xa0Goudenband "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                'score': u'93'},
 'Lindemans\xc2\xa0Framboise': {'result': {u'Description': u'Lindemans Framboise - Brouwerij Lindemans. Displayed for educational use only; do not reuse. Tweet. ... 88 out of 100 based on 1,375 user ratings. Sign Up Now!',
                                           u'DisplayUrl': u'beeradvocate.com/beer/profile/187/599/?ba=garfscores',
                                           u'ID': u'7be37fbe-679c-4e21-be59-1957f65c2563',
                                           u'Title': u'Lindemans Framboise - Brouwerij Lindemans - Vlezenbeek, Belgium ...',
                                           u'Url': u'http://beeradvocate.com/beer/profile/187/599/?ba=garfscores',
                                           u'__metadata': {u'type': u'WebResult',
                                                           u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Lindemans\xa0Framboise "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                'score': u'88'},
 'Local Option\xc2\xa0Dampf Loc': {'result': {u'Description': u'"Local Option Dampf Loc is a modern interpretation of medieval Bavarian peasant ale brewed by the Local Option\u2019s very own ... 86 out of 100 based on 23 user ratings ...',
                                              u'DisplayUrl': u'beeradvocate.com/beer/profile/16773/75680',
                                              u'ID': u'26876cb7-862f-457d-ab87-b0e7994fb905',
                                              u'Title': u'Dampf Loc - Local Option - Chicago, IL - BeerAdvocate',
                                              u'Url': u'http://beeradvocate.com/beer/profile/16773/75680',
                                              u'__metadata': {u'type': u'WebResult',
                                                              u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Local Option\xa0Dampf Loc "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                   'score': u'86'},
 'Local Option\xc2\xa0Morning Wood': {'result': {u'Description': u'Morning Wood - Local Option. No picture uploaded. Have one? Upload it now. Tweet. BA SCORE 85 good-26 Ratings: ... 85 out of 100 based on 26 user ratings. Sign Up Now!',
                                                 u'DisplayUrl': u'beeradvocate.com/beer/profile/16773/76109',
                                                 u'ID': u'c8bca480-c48f-4f97-8a36-942865dc0ad2',
                                                 u'Title': u'Morning Wood - Local Option - Chicago, IL - BeerAdvocate',
                                                 u'Url': u'http://beeradvocate.com/beer/profile/16773/76109',
                                                 u'__metadata': {u'type': u'WebResult',
                                                                 u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Local Option\xa0Morning Wood "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                      'score': u'85'},
 'Magic Hat\xc2\xa0#9': {'result': {u'Description': u'Poured into Magic Hat #9 etched pint glass. A - Amber with one finger of head. ... 78 out of 100 based on 2,945 user ratings. Sign Up Now! Rate, Review & Track This Beer!',
                                    u'DisplayUrl': u'beeradvocate.com/beer/profile/96/299',
                                    u'ID': u'9e35481c-1dd5-4b74-b7b1-7fc4adcd9fef',
                                    u'Title': u'#9 - Magic Hat Brewing Company - South Burlington, VT - BeerAdvocate',
                                    u'Url': u'http://beeradvocate.com/beer/profile/96/299',
                                    u'__metadata': {u'type': u'WebResult',
                                                    u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Magic Hat\xa0&$skip=0&$top=1#9 "out of 100 based on" site:beeradvocate.com\''}},
                         'score': u'78'},
 'Maine\xc2\xa0Mean Old Tom': {'result': {u'Description': u'Mean Old Tom - Maine Beer Company. Displayed for educational use only; do not reuse. Tweet. BA SCORE 88 ... 88 out of 100 based on 567 user ratings. Sign Up Now!',
                                          u'DisplayUrl': u'beeradvocate.com/beer/profile/20681/56545',
                                          u'ID': u'fedc5e60-ff83-4850-9ca1-ee789e80a9c8',
                                          u'Title': u'Mean Old Tom - Maine Beer Company - Portland, ME - BeerAdvocate',
                                          u'Url': u'http://beeradvocate.com/beer/profile/20681/56545',
                                          u'__metadata': {u'type': u'WebResult',
                                                          u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Maine\xa0Mean Old Tom "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                               'score': u'88'},
 'Maine\xc2\xa0Peeper': {'result': {u'Description': u'This beer is an alias for Peeper Ale from Maine Beer Company. Aliases may occur when a brewery renames a beer for: ... N/A out of 100 based on 0 user ratings.',
                                    u'DisplayUrl': u'beeradvocate.com/beer/profile/20681/60891',
                                    u'ID': u'cbb6ac1d-85a4-49aa-846c-c4e7212d74ac',
                                    u'Title': u'Spring Peeper Ale - Maine Beer Company - Portland, ME - BeerAdvocate',
                                    u'Url': u'http://beeradvocate.com/beer/profile/20681/60891',
                                    u'__metadata': {u'type': u'WebResult',
                                                    u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Maine\xa0Peeper "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                         'score': u'N/A'},
 'Malmgard\xc2\xa0Belge': {'result': '', 'score': 'N/A'},
 'Mikkeller\xc2\xa019': {'result': {u'Description': u'That turned out to be a mirage, as Mikkeller came back and made more. This 19 IPA blend is a good drink. Serving type: bottle ... 88 out of 100 based on 103 user ratings.',
                                    u'DisplayUrl': u'beeradvocate.com/beer/profile/13307/73551',
                                    u'ID': u'6413222a-573e-4917-ac4d-278f724130d5',
                                    u'Title': u'19 - Mikkeller ApS - K\xf8benhavn, Denmark - BeerAdvocate',
                                    u'Url': u'http://beeradvocate.com/beer/profile/13307/73551',
                                    u'__metadata': {u'type': u'WebResult',
                                                    u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Mikkeller\xa019 "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                         'score': u'88'},
 'Mikkeller\xc2\xa0Yeast Series 2.0 Brett Bruxellensis': {'result': {u'Description': u'Ratings for Yeast Series 2.0: Brettanomyces Bruxellensis; ... other beers in the Yeast 2.0 series and would gladly drink Brett Brux ... N/A out of 100 based on 9 user ...',
                                                                     u'DisplayUrl': u'beeradvocate.com/beer/profile/13307/90052/?ba=bmur112',
                                                                     u'ID': u'5713a1c0-7933-4f4b-8b74-e0ad935435b5',
                                                                     u'Title': u'Yeast Series 2.0: Brettanomyces Bruxellensis - Mikkeller ApS ...',
                                                                     u'Url': u'http://beeradvocate.com/beer/profile/13307/90052/?ba=bmur112',
                                                                     u'__metadata': {u'type': u'WebResult',
                                                                                     u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Mikkeller\xa0Yeast Series 2.0 Brett Bruxellensis "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                                          'score': u'N/A'},
 'Mikkeller\xc2\xa0Yeast Series 2.0 Brett Lambicus': {'result': {u'Description': u'Ratings for Yeast Series 2.0: Brettanomyces Lambicus; ... Yeast Series 2.0: Brettanomyces Lambicus - Mikkeller. ... N/A out of 100 based on 6 user ratings.',
                                                                 u'DisplayUrl': u'beeradvocate.com/beer/profile/13307/89588/?ba=bradfordjohnson',
                                                                 u'ID': u'647900a8-321e-468e-81c2-2b61a22301c8',
                                                                 u'Title': u'Yeast Series 2.0: Brettanomyces Lambicus - Mikkeller - K\xf8benhavn ...',
                                                                 u'Url': u'http://beeradvocate.com/beer/profile/13307/89588/?ba=bradfordjohnson',
                                                                 u'__metadata': {u'type': u'WebResult',
                                                                                 u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Mikkeller\xa0Yeast Series 2.0 Brett Lambicus "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                                      'score': u'N/A'},
 'New Belgium/Dieu Du Ciel\xc2\xa0Heavenly Feijoa': {'result': {u'Description': u'Bomber served chilled into a New Belgium chalice. The Heavenly Feijoa Tripel is a pale amber color with ... 85 out of 100 based on 10 user ... (Le Trou Du Diable)',
                                                                u'DisplayUrl': u'beeradvocate.com/beer/profile/192/90121',
                                                                u'ID': u'5da227ff-fcc3-47cd-801f-513ececf00a5',
                                                                u'Title': u'Lips Of Faith - Heavenly Feijoa Tripel - New Belgium Brewing ...',
                                                                u'Url': u'http://beeradvocate.com/beer/profile/192/90121',
                                                                u'__metadata': {u'type': u'WebResult',
                                                                                u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'New Belgium/Dieu Du Ciel\xa0Heavenly Feijoa "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                                     'score': u'85'},
 'New Belgium\xc2\xa0Cascara Quad': {'result': {u'Description': u'Lips Of Faith - Cascara Quad - New Belgium Brewing. Picture being approved. Tweet. BA SCORE 82 good-17 Ratings: ... 82 out of 100 based on 17 user ratings. Sign Up Now!',
                                                u'DisplayUrl': u'beeradvocate.com/beer/profile/192/89936',
                                                u'ID': u'9daf4192-9447-469b-aad9-21ae907f78ca',
                                                u'Title': u'Lips Of Faith - Cascara Quad - New Belgium Brewing - Fort Collins ...',
                                                u'Url': u'http://beeradvocate.com/beer/profile/192/89936',
                                                u'__metadata': {u'type': u'WebResult',
                                                                u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'New Belgium\xa0Cascara Quad "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                     'score': u'82'},
 'New Belgium\xc2\xa0Fat Tire': {'result': {u'Description': u'Fat Tire Amber Ale - New Belgium Brewing. Displayed for educational use only; do not reuse. Tweet. BA SCORE 82 ... 82 out of 100 based on 3,714 user ratings. Sign Up Now!',
                                            u'DisplayUrl': u'beeradvocate.com/beer/profile/192/607',
                                            u'ID': u'9c43b7dc-5d77-4dd9-833b-700b072f7029',
                                            u'Title': u'Fat Tire Amber Ale - New Belgium Brewing - Fort Collins, CO ...',
                                            u'Url': u'http://beeradvocate.com/beer/profile/192/607',
                                            u'__metadata': {u'type': u'WebResult',
                                                            u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'New Belgium\xa0Fat Tire "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                 'score': u'82'},
 'Oskar Blues\xc2\xa0Gubna': {'result': {u'Description': u'GUBNA Imperial IPA - Oskar Blues Grill & Brew. Displayed for educational use only; do not reuse. Tweet. ... 84 out of 100 based on 1,238 user ratings. Sign Up Now!',
                                         u'DisplayUrl': u'beeradvocate.com/beer/profile/2681/55412',
                                         u'ID': u'e017a4c6-d4dd-47fb-b05a-e0455214662b',
                                         u'Title': u'GUBNA Imperial IPA - Oskar Blues Grill & Brew - Lyons, CO ...',
                                         u'Url': u'http://beeradvocate.com/beer/profile/2681/55412',
                                         u'__metadata': {u'type': u'WebResult',
                                                         u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Oskar Blues\xa0Gubna "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                              'score': u'84'},
 'Oxbow\xc2\xa0Farmhouse pale': {'result': {u'Description': u'Oxbow Farmhouse Pale Ale pours a hazy, hay yellow with a big, frothy white head. ... 93 out of 100 based on 72 user ratings. Sign Up Now! Rate, Review & Track This Beer!',
                                            u'DisplayUrl': u'beeradvocate.com/beer/profile/26439/72219',
                                            u'ID': u'68ec2fb5-cdef-423c-9fe0-e8a3e7ddde86',
                                            u'Title': u'Farmhouse Pale Ale - Oxbow Brewing Company - Newcastle, ME ...',
                                            u'Url': u'http://beeradvocate.com/beer/profile/26439/72219',
                                            u'__metadata': {u'type': u'WebResult',
                                                            u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Oxbow\xa0Farmhouse pale "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                 'score': u'93'},
 'Oxbow\xc2\xa0Freestyle 13': {'result': {u'Description': u'Freestyle Series #13 - Oxbow Brewing Company. No picture uploaded. Have one? ... N/A out of 100 based on 5 user ratings. Sign Up Now! Rate, Review & Track This Beer!',
                                          u'DisplayUrl': u'beeradvocate.com/beer/profile/26439/89306',
                                          u'ID': u'c1b5a2e3-f38d-4dac-bbaa-0fb81adc55c6',
                                          u'Title': u'Freestyle Series #13 - Oxbow Brewing Company - Newcastle, ME ...',
                                          u'Url': u'http://beeradvocate.com/beer/profile/26439/89306',
                                          u'__metadata': {u'type': u'WebResult',
                                                          u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Oxbow\xa0Freestyle 13 "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                               'score': u'N/A'},
 'Oxbow\xc2\xa0Space Cowboy': {'result': {u'Description': u'Space Cowboy Country Ale from Oxbow Brewing Company. 86 out of 100 based on 24 user ratings. Sign Up Now! Rate, Review & Track This Beer!',
                                          u'DisplayUrl': u'beeradvocate.com/beer/profile/26439/79806/?ba=Thorpe429',
                                          u'ID': u'aff4ae81-5d54-4f5d-acb1-02e5d34d7530',
                                          u'Title': u'Space Cowboy Country Ale - Oxbow Brewing Company - Newcastle, ME ...',
                                          u'Url': u'http://beeradvocate.com/beer/profile/26439/79806/?ba=Thorpe429',
                                          u'__metadata': {u'type': u'WebResult',
                                                          u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Oxbow\xa0Space Cowboy "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                               'score': u'86'},
 'Prairie\xc2\xa0Standard': {'result': {u'Description': u'Prairie Standard - Prairie Artisan Ales. Picture being approved. Tweet. BA SCORE 88 good-43 Ratings: THE BROS ... 88 out of 100 based on 43 user ratings. Sign Up Now!',
                                        u'DisplayUrl': u'beeradvocate.com/beer/profile/30356/88169/?ba=garrisonp',
                                        u'ID': u'be283862-73b8-443c-803e-f7f00bcd26d5',
                                        u'Title': u'Prairie Standard - Prairie Artisan Ales - Krebs, OK - BeerAdvocate',
                                        u'Url': u'http://beeradvocate.com/beer/profile/30356/88169/?ba=garrisonp',
                                        u'__metadata': {u'type': u'WebResult',
                                                        u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Prairie\xa0Standard "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                             'score': u'88'},
 'Pub Dog\xc2\xa0Sour Cherry Porter': {'result': {u'Description': u'Ratings for Sour Cherry Porter; ... just part of an excellent draught selection at the Portland pub last weekend. ... N/A out of 100 based on 1 user ratings.',
                                                  u'DisplayUrl': u'beeradvocate.com/beer/profile/63/63951',
                                                  u'ID': u'227ce16e-8eb1-474e-af94-b3ca22eb511d',
                                                  u'Title': u'Sour Cherry Porter - Deschutes Brewery - Bend, OR - BeerAdvocate',
                                                  u'Url': u'http://beeradvocate.com/beer/profile/63/63951',
                                                  u'__metadata': {u'type': u'WebResult',
                                                                  u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Pub Dog\xa0Sour Cherry Porter "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                       'score': u'N/A'},
 'Ritterguts\xc2\xa0Gose': {'result': {u'Description': u'D\xf6llnitzer Ritterguts Gose - Brauhaus Hartmannsdorf GmbH. Displayed for educational use only; do not reuse. Tweet. ... 88 out of 100 based on 40 user ratings.',
                                       u'DisplayUrl': u'beeradvocate.com/beer/profile/7715/11218',
                                       u'ID': u'7c1ca08d-6fee-4ab2-a1eb-c1d899439aaa',
                                       u'Title': u'D\xf6llnitzer Ritterguts Gose - Brauhaus Hartmannsdorf GmbH ...',
                                       u'Url': u'http://beeradvocate.com/beer/profile/7715/11218',
                                       u'__metadata': {u'type': u'WebResult',
                                                       u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Ritterguts\xa0Gose "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                            'score': u'88'},
 'Rodenbach\xc2\xa0Classic': {'result': {u'Description': u"I picked up a bottle of Rodenbach's Rodenbach Classic last month for $2.69 at The Lager Mill. ... 91 out of 100 based on 828 user ratings. Sign Up Now!",
                                         u'DisplayUrl': u'beeradvocate.com/beer/profile/216/1882',
                                         u'ID': u'299b8877-364f-45ca-89a8-c09f87fdddc2',
                                         u'Title': u'Rodenbach Classic (Red) - Brouwerij Rodenbach N.V. - Roeselare ...',
                                         u'Url': u'http://beeradvocate.com/beer/profile/216/1882',
                                         u'__metadata': {u'type': u'WebResult',
                                                         u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Rodenbach\xa0Classic "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                              'score': u'91'},
 'Saint Helene\xc2\xa0Simcoe Lager': {'result': '', 'score': 'N/A'},
 'Scheldebrouwerij\xc2\xa0De Zeezuiper': {'result': {u'Description': u'Zeezuiper from Scheldebrouwerij. 83 out of 100 based on 41 user ratings. ... (Brouwerij der St. Benedictusabdij de Achelse)',
                                                     u'DisplayUrl': u'beeradvocate.com/beer/profile/552/24309',
                                                     u'ID': u'f362aaec-1895-42c0-bf91-082ead218ec5',
                                                     u'Title': u'Zeezuiper - Scheldebrouwerij - Meer, Belgium - BeerAdvocate',
                                                     u'Url': u'http://beeradvocate.com/beer/profile/552/24309',
                                                     u'__metadata': {u'type': u'WebResult',
                                                                     u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Scheldebrouwerij\xa0De Zeezuiper "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                          'score': u'83'},
 'Smisje\xc2\xa0Wostyntje': {'result': {u'Description': u'Wostyntje - Brouwerij Smisje. Displayed for educational use only; do not reuse. Tweet. BA SCORE 81 good- ... 81 out of 100 based on 162 user ratings. Sign Up Now!',
                                        u'DisplayUrl': u'beeradvocate.com/beer/profile/322/9749',
                                        u'ID': u'7cbb001e-7710-4ac4-aa0e-dfd2e7f150c4',
                                        u'Title': u'Wostyntje - Brouwerij Smisje - Oudenaarde, Belgium - BeerAdvocate',
                                        u'Url': u'http://beeradvocate.com/beer/profile/322/9749',
                                        u'__metadata': {u'type': u'WebResult',
                                                        u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Smisje\xa0Wostyntje "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                             'score': u'81'},
 'Steigl\xc2\xa0Lager': {'result': {u'Description': u'On tap at the Kaiserhof Restaurant in San Diego where they call this "Stiegl Premium Lager." ... 80 out of 100 based on 183 user ratings. Sign Up Now!',
                                    u'DisplayUrl': u'beeradvocate.com/beer/profile/817/3319',
                                    u'ID': u'b53362af-cbc2-44e4-b577-8f82a99dfde1',
                                    u'Title': u'Stiegl Goldbr\xe4u - Stieglbrauerei zu Salzburg GmbH - Salzburg ...',
                                    u'Url': u'http://beeradvocate.com/beer/profile/817/3319',
                                    u'__metadata': {u'type': u'WebResult',
                                                    u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Steigl\xa0Lager "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                         'score': u'80'},
 'Stillwater Ales\xc2\xa0Classique': {'result': '', 'score': 'N/A'},
 'Stillwater Ales\xc2\xa0Jaded': {'result': {u'Description': u'Ratings for Jaded (Import Series Vol ... Belgian Strong Dark Ale style beer brewed by Stillwater Artisanal Ales in Baltimore, ... 91 out of 100 based on 81 user ratings.',
                                             u'DisplayUrl': u'beeradvocate.com/beer/profile/22150/66573',
                                             u'ID': u'7fcc6d84-e3cb-4b88-b809-513152225f6d',
                                             u'Title': u'Jaded (Import Series Vol. 3) - Stillwater Artisanal Ales ...',
                                             u'Url': u'http://beeradvocate.com/beer/profile/22150/66573',
                                             u'__metadata': {u'type': u'WebResult',
                                                             u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Stillwater Ales\xa0Jaded "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                  'score': u'91'},
 'Stillwater/Hof Ten Dormaal\xc2\xa0Bronze Age': {'result': {u'Description': u'Ratings for Stillwater / Hof Ten Dormaal Bronze Age; ... 88 out of 100 based on 85 user ratings. Sign Up Now! Rate, Review & Track This Beer!',
                                                             u'DisplayUrl': u'beeradvocate.com/beer/profile/22150/77865',
                                                             u'ID': u'8c6957ab-e0df-4605-8322-3c9fb6620304',
                                                             u'Title': u'Stillwater / Hof Ten Dormaal Bronze Age - Stillwater Artisanal ...',
                                                             u'Url': u'http://beeradvocate.com/beer/profile/22150/77865',
                                                             u'__metadata': {u'type': u'WebResult',
                                                                             u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Stillwater/Hof Ten Dormaal\xa0Bronze Age "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                                  'score': u'88'},
 'Stillwater\xc2\xa0Lower Dens': {'result': {u'Description': u'Sensory Series V.1 - Lower Dens - Stillwater Artisanal Ales. Displayed for educational use only; do not reuse. Tweet. ... 88 out of 100 based on 25 user ratings.',
                                             u'DisplayUrl': u'beeradvocate.com/beer/profile/22150/88476',
                                             u'ID': u'5b38c3b3-bc98-4eac-8a07-2378e5ec7a89',
                                             u'Title': u'Sensory Series V.1 - Lower Dens - Stillwater Artisanal Ales ...',
                                             u'Url': u'http://beeradvocate.com/beer/profile/22150/88476',
                                             u'__metadata': {u'type': u'WebResult',
                                                             u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Stillwater\xa0Lower Dens "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                  'score': u'88'},
 'Strubbe\xc2\xa0Ichtegems Grand Cru': {'result': {u'Description': u"Ichtegem's Grand Cru - Brouwerij Strubbe. Displayed for educational use only; do not reuse. Tweet. BA SCORE 84 good- ... 84 out of 100 based on 300 user ratings.",
                                                   u'DisplayUrl': u'beeradvocate.com/beer/profile/2299/30358',
                                                   u'ID': u'cc90c372-16cd-41bd-ada3-518a30bfe99c',
                                                   u'Title': u"Ichtegem's Grand Cru - Brouwerij Strubbe - Ichtegem, Belgium ...",
                                                   u'Url': u'http://beeradvocate.com/beer/profile/2299/30358',
                                                   u'__metadata': {u'type': u'WebResult',
                                                                   u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Strubbe\xa0Ichtegems Grand Cru "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                        'score': u'84'},
 'Struise\xc2\xa0Black Damnation VII Single Black': {'result': {u'Description': u'Ratings for Black Damnation VII - Single Black; ... Black Damnation VII - Single Black - De Struise Brouwers. ... 83 out of 100 based on 26 user ratings.',
                                                                u'DisplayUrl': u'beeradvocate.com/beer/profile/15237/73451',
                                                                u'ID': u'a5882b82-c536-40c0-93f2-3b5accf82b27',
                                                                u'Title': u'Black Damnation VII - Single Black - De Struise Brouwers ...',
                                                                u'Url': u'http://beeradvocate.com/beer/profile/15237/73451',
                                                                u'__metadata': {u'type': u'WebResult',
                                                                                u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Struise\xa0Black Damnation VII Single Black "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                                     'score': u'83'},
 'Struise\xc2\xa0Pannepuet': {'result': {u'Description': u'Pannepot - De Struise Brouwers. Displayed for educational use only; do not reuse. Tweet. BA SCORE 97 world-class- ... 97 out of 100 based on 1,112 user ratings.',
                                         u'DisplayUrl': u'beeradvocate.com/beer/profile/15237/34306',
                                         u'ID': u'f3dc0530-7a74-4684-8819-af2afbad1873',
                                         u'Title': u'Pannepot - De Struise Brouwers - Oostvleteren, Belgium - BeerAdvocate',
                                         u'Url': u'http://beeradvocate.com/beer/profile/15237/34306',
                                         u'__metadata': {u'type': u'WebResult',
                                                         u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Struise\xa0Pannepuet "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                              'score': u'97'},
 'Struise\xc2\xa0Rio Reserva 2008': {'result': {u'Description': u'Rio Reserva - De Struise Brouwers. ... On-tap at Beachwood I, 2008 Vintage, A: ... 92 out of 100 based on 26 user ratings. Sign Up Now!',
                                                u'DisplayUrl': u'beeradvocate.com/beer/profile/15237/81244',
                                                u'ID': u'0072fbc8-a50a-4db5-8323-4c0861eb1923',
                                                u'Title': u'Rio Reserva - De Struise Brouwers - Oostvleteren, Belgium ...',
                                                u'Url': u'http://beeradvocate.com/beer/profile/15237/81244',
                                                u'__metadata': {u'type': u'WebResult',
                                                                u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Struise\xa0Rio Reserva 2008 "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                     'score': u'92'},
 'Struise\xc2\xa0Sint Amatus': {'result': {u'Description': u'... style beer brewed by De Struise Brouwers in Oostvleteren, ... Sint Amatus 12 is dark with tan head leaving scattered, ... 94 out of 100 based on 156 user ratings.',
                                           u'DisplayUrl': u'beeradvocate.com/beer/profile/15237/58905',
                                           u'ID': u'4d24b903-3797-43df-a58c-77e7259dd4ef',
                                           u'Title': u'St. Amatus 12 - De Struise Brouwers - Oostvleteren, Belgium ...',
                                           u'Url': u'http://beeradvocate.com/beer/profile/15237/58905',
                                           u'__metadata': {u'type': u'WebResult',
                                                           u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Struise\xa0Sint Amatus "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                'score': u'94'},
 'Struise\xc2\xa0Tsjeeses': {'result': {u'Description': u'Struise Tsjeeses De Struise Brouwers Appearance: A deep golden orange with some yeast sediment after a careful pour. ... 90 out of 100 based on 286 user ratings.',
                                        u'DisplayUrl': u'beeradvocate.com/beer/profile/15237/34310',
                                        u'ID': u'600c95d6-d344-4c56-8769-2832a289bd66',
                                        u'Title': u'Struise Tsjeeses - De Struise Brouwers - Oostvleteren, Belgium ...',
                                        u'Url': u'http://beeradvocate.com/beer/profile/15237/34310',
                                        u'__metadata': {u'type': u'WebResult',
                                                        u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Struise\xa0Tsjeeses "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                             'score': u'90'},
 'Struise\xc2\xa0XX': {'result': {u'Description': u'78 out of 100 based on 357 user ratings. Sign Up Now! Rate, Review & Track This Beer! ... Struise Kloeke Blonde (De Struise Brouwers) Follow BeerAdvocate.',
                                  u'DisplayUrl': u'beeradvocate.com/beer/profile/35/77233',
                                  u'ID': u'6217fafb-60f3-48b9-a881-6358a5f54f8c',
                                  u'Title': u'Belgian Session - Boston Beer Company (Samuel Adams) - Jamaica ...',
                                  u'Url': u'http://beeradvocate.com/beer/profile/35/77233',
                                  u'__metadata': {u'type': u'WebResult',
                                                  u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Struise\xa0XX "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                       'score': u'78'},
 'Struise\xc2\xa0XXX Rye Triple': {'result': {u'Description': u'XXX Rye Triple Ale - De Struise Brouwers. No picture uploaded. Have one? Upload it now. Tweet. BA SCORE N/A- ... N/A out of 100 based on 8 user ratings. Sign Up Now!',
                                              u'DisplayUrl': u'beeradvocate.com/beer/profile/15237/84618/?ba=metter98',
                                              u'ID': u'e072d2f7-5011-4414-a4c9-46e2e3ed1fa7',
                                              u'Title': u'XXX Rye Triple Ale - De Struise Brouwers - Oostvleteren, Belgium ...',
                                              u'Url': u'http://beeradvocate.com/beer/profile/15237/84618/?ba=metter98',
                                              u'__metadata': {u'type': u'WebResult',
                                                              u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Struise\xa0XXX Rye Triple "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                   'score': u'N/A'},
 'Struise\xc2\xa0XXXX Quad': {'result': {u'Description': u'Ratings for XXXX Quadruple Ale; Quadrupel (Quad) ... (Quad) style beer brewed by De Struise Brouwers in Oostvleteren, ... N/A out of 100 based on 5 user ratings.',
                                         u'DisplayUrl': u'beeradvocate.com/beer/profile/15237/84619/?ba=CheapBeerBuzz',
                                         u'ID': u'a1b5698e-d58c-4dcd-9a2d-75e37fe7fe5b',
                                         u'Title': u'XXXX Quadruple Ale - De Struise Brouwers - Oostvleteren, Belgium ...',
                                         u'Url': u'http://beeradvocate.com/beer/profile/15237/84619/?ba=CheapBeerBuzz',
                                         u'__metadata': {u'type': u'WebResult',
                                                         u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Struise\xa0XXXX Quad "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                              'score': u'N/A'},
 "Thornbridge\xc2\xa0Beadeca's Well": {'result': {u'Description': u"Ratings for Beadeca's Well; ... Beadeca's Well - Thornbridge Brewery. No picture uploaded. ... N/A out of 100 based on 2 user ratings.",
                                                  u'DisplayUrl': u'beeradvocate.com/beer/profile/13029/88457',
                                                  u'ID': u'c3935ad3-922d-42a8-b5cf-3c7a534b3cd2',
                                                  u'Title': u"Beadeca's Well - Thornbridge Brewery - Bakewell, United Kingdom ...",
                                                  u'Url': u'http://beeradvocate.com/beer/profile/13029/88457',
                                                  u'__metadata': {u'type': u'WebResult',
                                                                  u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Thornbridge\xa0Beadeca\'s Well "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                       'score': u'N/A'},
 'To Ol/Mikkeller\xc2\xa0Ov Ral IIPA': {'result': {u'Description': u"Ratings for Ov-ral; ... it's a fantastic Orval clone, a merger of Gueuze and IIPA qualities worth seeking out ... 88 out of 100 based on 36 user ratings.",
                                                   u'DisplayUrl': u'beeradvocate.com/beer/profile/24299/81795/?ba=pixieskid',
                                                   u'ID': u'95fd7cc8-8334-49ef-96ab-848cbdccb64e',
                                                   u'Title': u'Ov-ral - To \xd8l - Frederiksberg C, Denmark - BeerAdvocate',
                                                   u'Url': u'http://beeradvocate.com/beer/profile/24299/81795/?ba=pixieskid',
                                                   u'__metadata': {u'type': u'WebResult',
                                                                   u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'To Ol/Mikkeller\xa0Ov Ral IIPA "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                        'score': u'88'},
 'Trois Dames\xc2\xa0Grande Dame': {'result': {u'Description': u'Grande Dame Oud Bruin - Brasserie Trois Dames. Displayed for educational use only; do not reuse. Tweet. ... 87 out of 100 based on 46 user ratings. Sign Up Now!',
                                               u'DisplayUrl': u'beeradvocate.com/beer/profile/17998/54750/?ba=Beerenauslese',
                                               u'ID': u'f8acb187-1b48-45e5-bc53-64c62f497b1f',
                                               u'Title': u'Grande Dame Oud Bruin - Brasserie Trois Dames - Sainte-Croix ...',
                                               u'Url': u'http://beeradvocate.com/beer/profile/17998/54750/?ba=Beerenauslese',
                                               u'__metadata': {u'type': u'WebResult',
                                                               u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Trois Dames\xa0Grande Dame "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                    'score': u'87'},
 "Trois Dames\xc2\xa0L'Amoureuse Blanche": {'result': {u'Description': u"Ratings for L'Amoureuse No. 2 Rouge; Lambic - Fruit style beer brewed by Brasserie Trois Dames in Sainte-Croix, ... N/A out of 100 based on 2 user ratings.",
                                                       u'DisplayUrl': u'beeradvocate.com/beer/profile/17998/89439/?ba=bmur112',
                                                       u'ID': u'91facb01-b46f-403e-be22-802fa7e67ada',
                                                       u'Title': u"L'Amoureuse No. 2 Rouge - Brasserie Trois Dames - Sainte-Croix ...",
                                                       u'Url': u'http://beeradvocate.com/beer/profile/17998/89439/?ba=bmur112',
                                                       u'__metadata': {u'type': u'WebResult',
                                                                       u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Trois Dames\xa0L\'Amoureuse Blanche "out of 100 based on" site:beeradvocate.com\'&$skip=1&$top=1'}},
                                            'score': u'N/A'},
 "Trois Dames\xc2\xa0L'Amoureuse Rouge": {'result': {u'Description': u"Ratings for L'Amoureuse No. 2 Rouge; Lambic - Fruit style beer brewed by Brasserie Trois Dames in Sainte-Croix, ... N/A out of 100 based on 2 user ratings.",
                                                     u'DisplayUrl': u'beeradvocate.com/beer/profile/17998/89439',
                                                     u'ID': u'd4aaf38e-fd80-44cb-93c1-12b4503ffb04',
                                                     u'Title': u"L'Amoureuse No. 2 Rouge - Brasserie Trois Dames - Sainte-Croix ...",
                                                     u'Url': u'http://beeradvocate.com/beer/profile/17998/89439',
                                                     u'__metadata': {u'type': u'WebResult',
                                                                     u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Trois Dames\xa0L\'Amoureuse Rouge "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                          'score': u'N/A'},
 'Union\xc2\xa0Balt Alt': {'result': {u'Description': u'... Altbier style beer brewed by Union Craft Brewing Company in Baltimore, ... 86 out of 100 based on 16 user ratings. ... Im F\xfcchschen Alt',
                                      u'DisplayUrl': u'beeradvocate.com/beer/profile/29377/82924',
                                      u'ID': u'6f4e343e-f6ac-4b00-933b-38552afdb11f',
                                      u'Title': u'Balt Altbier - Union Craft Brewing Company - Baltimore, MD ...',
                                      u'Url': u'http://beeradvocate.com/beer/profile/29377/82924',
                                      u'__metadata': {u'type': u'WebResult',
                                                      u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Union\xa0Balt Alt "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                           'score': u'86'},
 'Union\xc2\xa0Duckpin Pale Ale': {'result': {u'Description': u'Duckpin Pale Ale - Union Craft Brewing Company. No picture uploaded. Have one? ... 87 out of 100 based on 24 user ratings. Sign Up Now! Rate, Review & Track This Beer!',
                                              u'DisplayUrl': u'beeradvocate.com/beer/profile/29377/82921',
                                              u'ID': u'049626a7-7ea9-4b98-beab-f7f878c3b614',
                                              u'Title': u'Duckpin Pale Ale - Union Craft Brewing Company - Baltimore, MD ...',
                                              u'Url': u'http://beeradvocate.com/beer/profile/29377/82921',
                                              u'__metadata': {u'type': u'WebResult',
                                                              u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Union\xa0Duckpin Pale Ale "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                   'score': u'87'},
 'Union\xc2\xa0Rye Baby IPA': {'result': {u'Description': u'Ratings for Rye IPA; ... N/A out of 100 based on 1 user ratings. Sign Up Now! ... Fuzzy Baby Ducks IPA (New England Brewing Co.) Susan',
                                          u'DisplayUrl': u'beeradvocate.com/beer/profile/29971/89403/?ba=JustinMatthew',
                                          u'ID': u'ee0eb558-e6b0-4f68-8443-42f0834f0a78',
                                          u'Title': u'Rye IPA - Vault Brewing Company - Yardley, PA - BeerAdvocate',
                                          u'Url': u'http://beeradvocate.com/beer/profile/29971/89403/?ba=JustinMatthew',
                                          u'__metadata': {u'type': u'WebResult',
                                                          u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Union\xa0Rye Baby IPA "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                               'score': u'N/A'},
 'Vapeur\xc2\xa0Saison De Pipaix': {'result': {u'Description': u'Saison De Pipaix - Brasserie \xe0 Vapeur. Displayed for educational use only; do not reuse. Tweet. BA SCORE 83 ... 83 out of 100 based on 175 user ratings. Sign Up Now!',
                                               u'DisplayUrl': u'beeradvocate.com/beer/profile/841/3392',
                                               u'ID': u'365486fb-b238-4c7b-bfd9-f3fbd87bbc81',
                                               u'Title': u'Saison De Pipaix - Brasserie \xe0 Vapeur - Pipaix-Leuze, Belgium ...',
                                               u'Url': u'http://beeradvocate.com/beer/profile/841/3392',
                                               u'__metadata': {u'type': u'WebResult',
                                                               u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Vapeur\xa0Saison De Pipaix "out of 100 based on" site:beeradvocate.com\'&$skip=0&$top=1'}},
                                    'score': u'83'},
 'Yuengling\xc2\xa0Lager': {'result': {u'Description': u'Ratings for Yuengling Traditional Lager; ... 78 out of 100 based on 2,846 user ratings. Sign Up Now! Rate, Review & Track This Beer!',
                                       u'DisplayUrl': u'beeradvocate.com/beer/profile/23980/1351/?ba=MDF',
                                       u'ID': u'f89402cf-63ec-4507-adcf-e6da353c93a8',
                                       u'Title': u'Yuengling Traditional Lager - Yuengling Brewery - - BeerAdvocate',
                                       u'Url': u'http://beeradvocate.com/beer/profile/23980/1351/?ba=MDF',
                                       u'__metadata': {u'type': u'WebResult',
                                                       u'uri': u'https://api.datamarket.azure.com/Data.ashx/Bing/SearchWeb/v1/Web?Query=\'Yuengling\xa0Lager "out of 100 based on" site:beeradvocate.com\'&$skip=1&$top=1'}},
                            'score': u'78'}}
